- examples/rdkafka_example.cpp
- src-cpp/rdkafkacpp_int.h
This should fix #187 by adding a key_ member to the message implementation and returning that as key (or NULL if they key is empty/unset).
The C++ example prints the key if present, like the C example does. None of the examples actually produce keys (so this code was tested with a temporary example code).
> Implement Message::key() in C++ interface

- Makefile
- src-cpp/Makefile
- src/Makefile
Mainly a case of defining "file-check" to depend on the recipes that build the files that file-check will check.
This fixes #179 for me, but one is never quite sure with "make -j" :-P
> Added target dependencies for "make -j".

- README.md
The linked PHP extension repo is no longer being developed. I've changed the link to the only fork that is being developed ATM. I'm trying to advertise the fact that PHP-Kafka integration is being worked on, hoping to get some feedback, and possibly contributions to get a usable extension out there ASAP.
Cheers
> Update readme: PHP extension is not being developed by salebab anymore

- src/rdkafka.h
- src/rdkafka_msg.c
For our particular use case mapping keyed messages on to a consistent partition is important, it's probably important for anyone who wants to use log compaction.  I'm not sure what you'd want in terms of tests so I've done nothing. :trollface: 
Uses rd's crc32 to hash keys ensuring that the same key will map to the same partition.
Similar in spirit to the Scala code's default partitioner:
```scala
def partition(key: Any, numPartitions: Int): Int = {
Utils.abs(key.hashCode) % numPartitions
}
```
> Add a built in consistent hashing partitioner

- src/rdkafka_broker.c
rd_kafka_toppar_offsetcommit_request writes topic-level rkt_conf.group_id into the request, but uses the global-level rk_conf.group_id for buffer sizing.
> use topic level group_id for rkbuf sizing

- src/rdkafka_msg.c
Minor API usability tweak. I was producing messages with a NULL payload, but a non-zero payload length. This causes an invalid produce request to be sent to the Kafka broker, and the broker responds by logging an exception (java.nio.BufferUnderflowException) and closing the connection.
Test case: https://gist.github.com/ept/a7d6edc2e46f896b03a6
This is really my mistake for passing invalid parameters to rd_kafka_produce. However, it might be nicer if the length parameters are ignored if NULL data is passed in, rather than creating an invalid produce request. This simple patch forces the length to be zero in that case.
> Ignore supplied key or payload length if the pointer is null

- examples/rdkafka_example.cpp
- src-cpp/ConsumerImpl.cpp
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
* New base class ConsumeCb allows for easy definition of consume_callback classes.
* New function Consumer::consume_callback consumes as many messages as possible, calls ConsumeCb::consume_cb for each message.
* Example C++ code re-organized a little; function msg_consume extracted from loop, prints on cout instead of cerr.
Implements #168, implements #245.
> Added Consumer::consume_callback as front-end of rd_kafka_consume_callback

- README.md
php-rdkafka is a thin PHP binding for librdkafka. Although it uses classes, it attempts to not deviate from librdkafka's API.
> Updated README: Added php-rdkafka

- src-cpp/rdkafkacpp.h
- src/rdkafka.h
- src/rdkafka_msg.c
RD_KAFKA_MSG_F_FREE was specified.  (Issue #298)
> rd_kafka_msg_new() should never free the payload on failure if

- src/rdkafka_transport.c
Use SSL_CTX_use_certificate_chain_file() instead of SSL_CTX_use_certificate_file() to allow the use of complete certificate chains for TLS client authentication.
> Support certificate chains for TLS client authentication

- rpm/librdkafka.spec
Pkgconfig files were missing from -devel package RPM spec, failing 'make rpm' with unpackaged files.
> Add pkg-config files to -devel RPM spec

- configure.librdkafka
This PR makes SASL support configurable with `--enable-sasl` and `--disable-sasl` flags.
> Make SASL support configurable

- src/rdkafka_offset.c
If a file is opened in `a+` mode, output is always appended to the end of file.
Therefore, in function `rd_kafka_offset_file_commit` ( https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_offset.c#L260-L342 ), `fseek` is ignored and offset file is not updated.
> Fix offset commit bug

- src/rdkafka_timer.c
Idle consumers on Win used ~3-4% CPU without doing anything. Turns out they spent their time in a loop in rd_kafka_timers_run, because rd_clock only updates every now and then.
So make it only loop once if called with RD_POLL_NOWAIT, even if rd_clock doesn't change.
This brings idle CPU usage down to practically nothing. The same issue affects osx, but there the effect was smaller, I suspect linux is similar.
> Don't busy loop in rd_kafka_timers_run

- src-cpp/ConsumerImpl.cpp
`consumer_callback` does not pass opaque to `consume_cb`.
> Fix consumer_callback does not pass opaque to consume_cb

- src/rdaddr.c
- src/rdcrc32.h
- src/rdkafka.c
- src/rdkafka_assignor.c
- src/rdkafka_assignor.h
- src/rdkafka_broker.c
- src/rdkafka_buf.c
- src/rdkafka_buf.h
- src/rdkafka_conf.c
- src/rdkafka_msg.c
- src/rdkafka_offset.c
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_pattern.c
- src/rdkafka_pattern.h
- src/rdkafka_proto.h
- src/rdkafka_request.c
- src/rdkafka_transport.c
- src/rdkafka_transport.h
- src/rdrand.c
- src/trex.h
- win32/librdkafka.vcxproj
I'm trying to get librdkafka to compile 100% clean with msvc, clang and gcc.
This got longer than expected, so I would appreciate if you had a look.
It's not finished yet, but the remaining warnings are all about rather tricky issues.
Mostly replacing ints with size_t where the int was actually just assigned to the return value of something like strlen or where the value is passed to something like malloc.
Watch out for cases where I might have overlooked things that are now size_ts might actually be negative. I think I got them all now, but best to triple-check.
How would you prefer to continue with this? I think part of this PR should be fairly uncontroversial, another part needs checking by you, and then there's also a bunch of remaining warnings left.
Tests pass on win32/64 and with …
> Compile cleanly / sort out sizeof(size_t) != sizeof(int)

- src/snappy.c
- src/win32_config.h
- win32/librdkafka.vcxproj
- win32/tests/tests.vcxproj
- win32/tests/tests.vcxproj.filters
rd_ctz had _BitScanReverse mixed up with _BitScanForward, after that it just worked.
Also puts in a couple of casts to make it not complain during compilation, because snappy is quite optimized.
> Fix snappy on win32

- lds-gen.py
After the change to rewrite the lds-gen script in Python (in 0fdac6aa), internal symbols are exported in the shared libraries. This branch undoes the change.
The extra exported symbols somehow prevented my application from working, but I haven't tracked down how this happened.
> Stop exporting internal symbols from shared libraries

- src/rdkafka.h
- src/rdkafka_msg.c
- src/rdkafka_topic.c
- tests/0006-symbols.c
Set default partitioner to _consistent_ (rather than _random_) to behave more like Java/Scala implementations. Closes Issue #546
> Change default partitioner to consistent-random (closes #546)

- src-cpp/rdkafkacpp.h
This ensures that the objects are properly cleaned up and also solves compilation issue when flag -Werror=non-virtual-dtor is present.
> added virtual destructors to all classes that have a virtual function

- tests/0012-produce_consume.c
- tests/0018-cgrp_term.c
- tests/0022-consume_batch.c
- tests/0029-assign_offset.c
These tests were failing because they were trying to publish to partitions that didn't exist (topics were being created with 1 partition (default)).
> test-suite-fix: tests that expect more than one partition now create topic ahead-of-time

- CONFIGURATION.md
- src/rdkafka_conf.c
- src/rdkafka_conf.h
- src/rdkafka_transport.c
By default, OpenSSL will ignore any CRL provided in the CA. With this
option, a user can provide a specific CRL file and, in this case, we
also instruct OpenSSL to do a CRL check when verifying a remote
certificate. If a user wants OpenSSL to check the CRL embedded in a CA,
they can just provide the CA instead of the CRL.
> Add ability to specify a CRL for checking remote certificates

- examples/rdkafka_example.c
- src/rdlog.c
gcc 5.1 complains 
rdlog.c:39:6: error: assuming signed overflow does not occur when
assuming that (X + c) >= X is always true [-Werror=strict-overflow]
> Fix a potential signed integer overflow that gcc 5.1 complains about

- src/rdkafka_offset.c
This seemed to be needed, but alas I don't have good notes on the exact problem that not doing it caused.  (I'm trying to catch you up on outstanding patches I have that might be of general use.)
> Initialize rktp_stored_offset after loading from a file.

- README.win32
- win32/librdkafka.sln
- win32/librdkafka.vcxproj
- win32/librdkafkacpp/librdkafkacpp.vcxproj
- win32/rdkafka_consumer_example_cpp/rdkafka_consumer_example_cpp.vcxproj
- win32/rdkafka_example/rdkafka_example.vcxproj
- win32/tests/tests.vcxproj
Thanks for a great product.
In building the WIN32 debug and release versions of all projects, a few inconsistencies were found (library paths and libraries missing, VS2015 toolset being referenced, etc.). These have all been fixed and now all 32-bit projects build. The resultant changes to the .sln and .vcxproj files are in the pull request.
Also, the README.win32 has been updated to state that Microsoft Visual Studio 2013 should be used, and that the latest v1.0.2 version of OpenSSL should be used, because the actual latest version v1.1.0 has a changed API and this breaks compilation.
> Fix tiny WIN32 problems building 32-bit debug and release projects.

- examples/rdkafka_consumer_example.c
- examples/rdkafka_example.c
Configuration on Linux 3.19.0-49-generic #55~14.04.1-Ubuntu x86_64 fails on C files in the examples directory because of missing getopt.h include.
```
CFLAGS="--std=c99 -g -O2" CXXFLAGS="--std=c++11 -g -O2" ./configure --no-download --disable-ssl --disable-sasl --prefix=/usr/local
(...)
make[1]: Entering directory `/home/julien/dev/github/librdkafka/examples'
gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith --std=c99 -g -O2     -I../src rdkafka_example.c -o rdkafka_example  \
../src/librdkafka.a -lpthread -lz   -lcrypto   -lrt
rdkafka_example.c: In function ‘main’:
rdkafka_example.c:303:2: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
while ((opt = getopt(argc, argv, "PCLt:p:b:z:qd:o:eX:As:")) != -1) {
^
rdkafka_example.c:311:12: …
```
> Examples require getopt header file to avoid 'optind' undeclared error

- INTRODUCTION.md
I just changed the order of your explanation in the introduction file so that it reflect the actual function.
Sorry for being pedantic.
> Change the order of parameter explanation in intro for rd_kafka_produce fn

- src/rdkafka_int.h
There is a pattern in the rd_kafka_curr_msgs_* functions in rdkafka_int.h to avoid referencing the rk_curr_msgs structure if the application is not a RD_KAFKA_PRODUCER.
However, for the rd_kafka_curr_msgs_get function, while there exists a check for RD_KAFKA_PRODUCER and return values are set to 0, there is no subsequent return statement and the function falls through to manipulating the rk_curr_msgs structure even when the application is not a RD_KAFKA_PRODUCER, causing exceptions on trying to lock the structure on WIN32.
This patch adds the missing return statement.
> Add missing return in rd_kafka_curr_msgs_get if RD_KAFKA_PRODUCER.

- src/rdkafka.c
- src/rdkafka.h
This patch allows the user to be sure the rd_kafka_conf_t* is only deleted on success when calling rd_kafka_new.
It works by first duplicating the user conf if supplied, or creating a new conf. This means that this duplicate conf may be deleted from the same places in rd_kafka_new as before.
At the end of rd_kafka_new: delete the user supplied conf to keep current behavior.
If we were to change behavior and have user create and delete conf, it's as easy as just deleting the last lines of function rd_kafka_new.
> rd_kafka_new: delete conf only on success

- src/rdkafka_cgrp.c
There is a race condition for offset store. `rd_kafka_cgrp_partitions_fetch_start` should not overwrite the stored offset except when it was first started.
> Only store initial offset when fetcher was first started

- src/rdkafka_queue.c
`rd_kafka_q_fix_offsets` purges messages by comparing a relative offset to the absolute min offset. It only works when the absolute min offset is 0.
> Fix relative offset calculation

- examples/rdkafka_performance.c
- src/rdkafka.c
- src/rdkafka_cgrp.c
- src/rdkafka_offset.c
- src/rdkafka_partition.c
- src/rdkafka_sasl.c
- src/rdkafka_timer.c
- src/rdkafka_timer.h
./rdkafka_performance -P -b xxxx:xx -t test_topic -i 3600000
% Configuration property "statistics.interval.ms" value -694967 is outside allowed range 0..86400000
statistics.interval.ms 86400000
int rtmr_interval max :  2147483647(2^31)
86400000 * 1000 > 2147483647(2^31)
> fix bug rd_kafka_timer_t microsecond interval overflow.

- src/rdatomic.h
This is to make atomic functions work  using native sun solaris compiler. I could not find any good way to do it thru config.
> Use compiler specific atomic ops for sun studio compiler

- src/snappy_compat.h
A few more changes for AIX:
1. malloc/calloc return NULL for 0 size memory request.
2. As described in issue  #837, need to use mutexes for atomic ops.
> Fix for AIX-- exclude endian.h on AIX

- src/snappy.c
Since  __builtin_clz, __builtin_ctz, __builtin_ctzll are not available for  AIX and Sun, provided the replacements
> Replacement for builtins for sun and ibm

- src/rdkafka_offset.c
- src/rdkafka_queue.h
While running tests on IBM-AIX, I experienced a crash while running 0030-offset_commit for  manual async commit. What's happening is that, it is evaluating both expressions and repq being NULL for async case, wreaks havoc when NULL is being passed to rd_kafka_q_keep().
> Fix for async offset commit issue on AIX

- README.win32
- src-cpp/rdkafkacpp.h
- src/rdkafka.h
I currently build librdkafka out of source with cmake but it would be convenient to make it possible to build static libs. This pull request only enables that - it does not change anything for existing builds.
> adds check of defined LIBRDKAFKA_STATICLIB to enable static library

- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
for issue #878
As the (C++) Conf setters do not forward callbacks in the C struct like with other parameters, special getter should be used to read the callbacks from the Conf.
This update also blocks the original Getter(String&, String&) to get the callbacks from the C struct.
> Enrichment of Conf getter for callbacks.

- src-cpp/TopicImpl.cpp
- src-cpp/rdkafkacpp.h
This patch fixes an issue when compiling code with librdkafka
with all optimizations disabled. The library declares a number
of static constant integer values in headers, but not in
compiled files. This causes any code that passes these constants
directly to a function accepting a const reference to result in
undefined reference errors when linking. The error is fixed by
also declaring the variables in their corresponding .cpp files.
This issue affects GCC when compiling with optimizations disabled.
> Fix undefined references to static const ints (961)

- src/rdkafka_broker.c
rd_kafka_broker_send may use the address of msg2, out of  scope
> fix: use out of scope variable

- configure.librdkafka
Previously, mklove activated lz4 support when lz4 was found. This added
a so called "automagic" dependency on liblz4 which is a problem from
distributions.
This commit will add an option which will allow you to explicit disable
lz4 usage.
> configure: Add option to disable automagic dependency on liblz4

- CMakeLists.txt
- packaging/cmake/Config.cmake.in
- src-cpp/CMakeLists.txt
- src/CMakeLists.txt
After install package can be found by [find_package](https://cmake.org/cmake/help/latest/command/find_package.html). Example:
```cmake
find_package(RdKafka CONFIG REQUIRED)
add_executable(rdkafka_example rdkafka_example.c)
target_link_libraries(rdkafka_example PUBLIC RdKafka::rdkafka)
add_executable(rdkafka_example_cpp rdkafka_example.cpp)
target_link_libraries(rdkafka_example_cpp PUBLIC RdKafka::rdkafka++)
```
> Add install target

- README.md
We use librdkafka to develop an embedded Lua script to consume Kafka data process service
Now we have open source it, we hope you add our project
Our project : https://github.com/weiboad/aidp
Thanks
> add weiboad/aidp project links

- configure.librdkafka
- src/rdendian.h
- src/rdkafka_broker.c
[SmartOS](https://www.joyent.com/smartos) is a derivative of Illumos, itself a derivative of Solaris. Building librdkafka's master branch on a 15.4 image of SmartOS failed with the following error:
```
[root@e31d952d-043b-4188-e3fa-9ae120820740 /var/tmp/gh-repos/librdkafka]# make -j 6
make[1]: Entering directory '/var/tmp/gh-repos/librdkafka/src'
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__ -DLIBRDKAFKA_GIT_VERSION="\"v0.9.4-132-g386516-dirty\""  -c rdkafka.c -o rdkafka.o
gcc -MD -MP -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D__EXTENSIONS__ -DLIBRDKAFKA_GIT_VERSION="\"v0.9.4-132-g386516-dirty\""  -c …
```
> fix build on SmartOS

- src/rdkafka_request.c
Fixes #1190 
`offsetsForTimes()` is failing when requesting offset for multiple partitions, which span multiple topics, on a single broker. This is because the number of partitions in the request was accumulated for all partitions, but should be per topic.
Note, there is no regression test in place yet, may want this before merging.
> Partition count should be per topic in offset request buffer

- src/rdendian.h
See [Issue #1156] for more info.
The two key things are:
1) getting __LITTLE_ENDIAN, __BIG_ENDIAN, and __BYTE_ORDER defined
properly
2) the (uint16_t) part of the
#define htole16(x) ((uint16_t)BSWAP_16(x))
line.
The cast is essential as otherwise in this part of a
macro in snappy_compat.h
typeof((v)) _v = (v); \
memcpy((x), &_v, sizeof(*(x))); })
the value of 'v' has typeof int, not uint16_t, and it takes the 32-bit
extended value and copies the first two bytes, which being big endian,
are zero and not the correct swapped value.
> Fix endianism issues that were causing snappy to compress incorrectly on SPARC

- README.md
I finally released cppkafka, my C++11 rdkafka wrapper, so I think it's a good idea to add it here.
> Add cppkafka to language bindings

- examples/rdkafka_performance.c
`rdkafka_performance` had the undocumented flag `-x` which causes the tool to hard exit after sending <cnt> messages. I documented this flag in the tool's help message.
> Documented hard exit flag for rdkafka_performance

- src/rdkafka.h
- src/rdkafka_broker.c
- src/rdkafka_msg.c
To avoid the case where a buggy application does not call poll()
and thus not serving delivery reports, the on_ack..() interceptor
is now called immediately from the broker thread when the
final delivery result is known.
> Call on_acknowledgement() interceptor from internal thread

- CONFIGURATION.md
- mklove/Makefile.base
- mklove/modules/configure.host
- src/rddl.c
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_conf.c
- src/rdkafka_interceptor.c
- src/rdkafka_interceptor.h
- src/rdkafka_msgset_reader.c
- src/rdlist.c
- src/rdlist.h
- src/rdstring.c
- src/win32_config.h
- tests/0004-conf.c
- tests/0064-interceptors.c
- tests/0066-plugins.cpp
- tests/CMakeLists.txt
- tests/Makefile
- tests/interceptor_test/interceptor_test.c
- tests/interceptor_test/interceptor_test.h
- tests/test.c
- tests/test.h
- win32/librdkafka.sln
- win32/tests/tests.vcxproj
This PR addresses:
* fixed how interceptors interact with configuration object copying.
* the platform-dependent shared-library filename extension is now appended if the initial load fails (allowing the same config  to be used on multiple platforms).
* minor small fixes
> Plugin fixes

- src/rdkafka_sasl_cyrus.c
sasl_client_new does not copy its callback argument array, resulting
in a pointer to transient stack memory. This patch moves the callbacks
array into the rd_kafka_cyrus_state_t which has the same lifetime
as the connection and thus will remain valid.
> sasl_cyrus: Fix dangling stack ptr to sasl_callback_t (#1329)

- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_buf.h
- src/rdkafka_request.c
- tests/0070-null_empty.cpp
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
This also fixes an off-by-one error for the Producer's returned offsets when produce.offset.report=false (default)
> Fix 1386, messed up Null/Empty handling in the Consumer

- examples/rdkafka_consumer_example.c
There is no "-s" command line option. The opaque pointer passed to
msg_consume is not used by that function.
> Remove unused parameters

- examples/rdkafka_performance.c
On linux once a process is done sleeping it takes about 5 microseconds
to start running again. By default linux allows 50 microseconds of
slack in the length of sleep() calls to optimize the number of wakeups.
The amount of timerslack can be reduced to 1 nanosecond, but the time
to get rescheduled and run does not appear to be easily modifiable.  As
a result it is not really possible to use a sleep() variant to wait for
less than 55 microseconds, and for lengths of time not much more than
that it will not be terribly accurate.  So if we need to produce
messages more frequently than every 100 microseconds we busy wait
instead of calling usleep().  100 is a somewhat arbitrary number, but
its close to twice the minimum length of time a process would sleep by
default.  This is also suboptimal …
> rdkafka-performance: busy wait to wait short periods of time

- src/rdkafka_lz4.c
Fix https://github.com/edenhill/librdkafka/issues/1445
Self-explanatory, see the issue description for details.
cc: @igorcanadi
> Do not assume LZ4 worst (best?) case 255x compression

- packaging/nuget/release.py
@edenhill - this is much easier than unzipping, manually editing files and re-zipping. I needed to automate this so it might as well be here.
> allow nuget version to be specified independent of version tag

- CMakeLists.txt
3.2 is maximal available version from ppa for ubuntu trusty
> Raise cmake minimum version to 3.2

- src-cpp/QueueImpl.cpp
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
Hi,
As discussed in, https://github.com/edenhill/librdkafka/issues/617, I've created a pull request.  Awaiting feedback.
Thanks,
Akhi
> Allow for calling rd_kafka_queue_io_event_enable() from the C++ world

- mklove/modules/configure.cc
Ccache can be used to speed up compiling. When using ccache, we usually
set following environments variables:
```
export CC="ccache gcc"
export CXX="ccache g++"
```
In current version of configure.cc, we pass $CXX to function
mkl_mkvar_set without quoting marks:
```
mkl_mkvar_set "CXX" CXX $CXX
```
mkl_mkvar_set actually receives 4 variables: CXX, CXX, ccache and g++,
then mkl_mkvar_set will set CXX to ccache, but not "ccache g++", thus
causes errors when compiling files in folder src-cpp.
> Make librdkafka compiles with ccache.

- src/rdkafka_queue.c
Waiting 0ms to be signaled the queue now contains elements doesn't
really mean anything.  However per the POSIX specification of
pthread_cond_timedwait() the lock must be released and reacquired.  As a
result if we skip calling cnd_timedwait() when the timeout is 0 we
improve average and best case latency in various conditions by between
0.1 and 0.2ms.
> stop calling cnd_timedwait() with a timeout of 0h

- README.md
I heard a colleague mention this lib but hard a hard time finding it, figured it would be nice to mention in the README.
> Mention rdkafka-ruby in README

- src/rdkafka.c
- src/rdkafka_conf.c
- src/rdkafka_conf.h
- src/rdkafka_transport.c
- src/rdkafka_transport_int.h
- tests/0004-conf.c
Added the feature to use PKCS#12 keystores as the repository for a client authentication connection
> PKCS#12 Keystore Enhancement

- src/rdatomic.h
The #cmakedefine01 always defines the names e.g. HAVE_ATOMICS_32 with
either 0 or 1, but the code in https://github.com/edenhill/librdkafka/blob/master/src/rdatomic.h makes checks such as:
```c
#ifndef HAVE_ATOMICS_32
mtx_t lock;
#endif
```
This will always compile support for atomics regardless of whether
it's supported or not.
> use #if instead of #ifdef / defined() for atomics

- src/rdkafka_partition.c
This fixes the issue where a consumer subscribes to a topic and then pause consumption where all consumer offsets are initially already EOF. Without this check, the offset that's used after resuming consumption is invalid, which ends up falling back to whatever `auto.reset.policy` is being used, which in turn makes the consumer "forget" about which offset was actually already committed.
This fixes #1307. I'm not sure if this has any undesired side effects but at least I'm sure I'm not hitting the issue anymore.
> Don't store invalid offset as next one when pausing

- src/rdkafka_msg.h
- src/rdkafka_partition.c
Holding locks across syscalls is generally not a great idea since it
means spending longer with the lock and increases the chances the
process will spend time holding the lock but descheduled.  In this case
it is especially unfortunate because the write will make a broker thread
runnable if it is blocked on poll, but if the broker thread runs before
the thread calling write() it will immediately block again trying to
take the toppar lock.  This appears to reduce worst case latency by at
least 1ms, and quiet possibly much more, its hard to know exactly how
much should be attributed to this instead of other freek events hurting
worst case latency.  Its somewhat unfortunate we need to do a little
more work unconditionally, but the atomic accesses can be optimized
somewhat, and it may be a …
> avoid holding the toppar lock across a write syscall

- src/CMakeLists.txt
Fix C2491: definition of dllimport static data member not allowed
> Fix build error on Windows

- CMakeLists.txt
- examples/CMakeLists.txt
- packaging/cmake/README.md
- src-cpp/CMakeLists.txt
- src/CMakeLists.txt
- src/win32_config.h
- tests/CMakeLists.txt
In Windows, the option WITH_PLUGINS is set to OFF, but in src/win32_config.h you can find #define WITH_PLUGINS 1.
This cause link errors when you link against librdkafka. So you have to manually set #define WITH_PLUGINS 0 for the cmake build to work properly.
> cmake build improve on windows

- src/rdkafka_broker.c
- src/rdkafka_op.c
A WAKEUP operation in a broker queue didn't trigger immediate wakeup (`rd_kafka_q_pop` didn't return on WAKEUP). This fix makes sure that the broker immediately stops waiting on its operation queue in case of wake-up, instead of waiting the timeout in `rd_kafka_broker_ops_serve`.
I noticed this problem while working on https://github.com/edenhill/librdkafka/pull/1659.
> Fix broker wake up

- src/rdkafka_transport.c
The typeof operator is non standard, and at least XLC doesn't support
it.  While the type of msghdr::msg_iovlen is a bit of a mess the largest
value we will ever want to store in it is IOV_MAX. IOV_MAX should be
much smaller than INT_MAX, and in both cases the array whose length we
are providing is on the stack, so it should easily fit in an int.  We
know that the length should be non negative, so it should be safe to
cast to int, and then allow C promotion rules to widen to the actual
type of msg_iovlen if larger.
> stop using typeof in rdkafka_transport.c

- INTRODUCTION.md
Fixes #1791
Also fixed a typo: "Test Detailts" => "Test Details"
It makes the document a tad bit uglier in plain-text mode but I believe the trade-off is okay, seeing as most people will be introduced through the GitHub interface for the first time.
> [Issues/1791] Add relative hyperlinks to table of contents in INTRODUCTION.md

- mklove/modules/configure.cc
This PR closes [Issue #1796 ](https://github.com/edenhill/librdkafka/issues/1796)
A log below shows that zlib, libcrypto, libssl are detected by pkg-config. A compilation was performed with a parameter `--pkg-config-path=$PKG_CONFIG_PATH`.
```
Removing config.log
rm -f config.log config.log.old
patching file mklove/modules/configure.cc
Hunk #1 succeeded at 169 (offset 2 lines).
patching file mklove/modules/configure.cc
checking for OS or distribution... ok (Ubuntu)
checking for C compiler from CC env... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for pkgconfig (by command)... ok
checking for install (by …
```
> [FIX] pkg-config detection of libraries does not work

- tests/gen-ssl-certs.sh
I promised a pull request in https://github.com/edenhill/librdkafka/issues/1765 and forgot about it. Not necessarily bad, because I found a few more things. In detail, this changes:
- specify the keyalg to be RSA as it may default to DSA, which Java/Kafka(?) does not cope well with
- pass the validity period when signing a non-java client key
- change the key length to the current "recommended" minimum
(The last one might not be the best idea, if you are also using this script in some kind of CI setting. Please tell me what you think.)
> Some small enhancements to gen-ssl-certs.sh

- src/rdkafka.h
- src/rdkafka_queue.c
- src/rdkafka_queue.h
- tests/0083-cb_event.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
See issue #1859.
I've added a test based on 0040. I'm not super happy with the sleep-based waiting loop, but even with a better approach I don't think we'd be able to reduce the execution time of the test by more than 2 seconds. Let me know if you have any suggestion.
> Add callback-based IO event notifications

- src/rdkafka_buf.h
(RD_KAFKAP_STR_LEN0(_klen) == 0) will treat zero-length as true as well,
and then assign NULL to kstr->str to cause segment fault in future access.
Fixed it by change it to (RD_KAFKAP_STR_IS_NULL(kstr))
> Fix a segment fault error in rdkafka_buf with zero-length string.

- src/rdkafka_conf.c
- tests/0004-conf.c
This helped me to find an issue in our configuration: node-rdkafka is lagging behind master (obviously), and the `consumer` value for the `debug` configuration option wasn't supported in that version yet.
> Log the value that couldn't be found for s2f configuration options

- src/rdkafka_partition.c
Just add a missing word in the documentation for a function.
> Missing word in documentation

- src/rdhdrhistogram.c
In rd_hdr_histogram_new() when minValue is 0, log2() will return -inf.
Casting -inf to int is undefined, and on MIPS this results in 2^31
but on other architectures it becomes zero instead (which is desired
in this function). Fix this by changing so the RD_MAX() compare
is done on floating point (0 is > -inf) and thus unitMagnitude
becomes 0 (as expected).
This bug caused the while() loop in said function to never terminate
which in turn caused the unit tests to hang.
> rdhdrhistogram: Fix incorrect float -> int cast causing havoc on MIPS.

- src/rdkafka.c
Fixes an error where a null mtx would attempted to be accessed within
RD_KAFKA_REPLYQ as tmpq would not be created if no timeout is provided.
> consumer: use RD_KAFKA_NO_REPLYQ when calling rd_kafka_seek async

- src/rdkafka_broker.c
- src/rdkafka_buf.c
- src/rdkafka_buf.h
- src/rdkafka_op.h
- src/rdkafka_request.c
There are multiple parts to this fix:
* A request/response handler can now check if a failing request
was sent out on the wire (or did not make it past the output
queue).
* The retry code now only increments the retry count for actually
sent requests.
* When the broker connection goes down, requests in the output queue
are now purged to have their handler callbacks called which in turn
will trigger a (now free) retry.
* ProduceRequests are not retried, but their messages are put back
on the partition queue (existing behaviour).
> Purge and retry buffers in outbuf queue on connection fail (#1913)

- examples/rdkafka_performance.c
Sleeping here means we won't be looking for delivery reports, which in latency mode
is problematic: The latency is calculated in the delivery report callback based on the time
when that is called, which would be offset by the slept time.
In my case I'm using the tool with low message rates (1-10 messages/s), and the latencies reported
by the producer ended up between 1s (1 message/s) and 100ms (10 messages/s). Looking into this
showed that the sleeping for the `rate_sleep` means that the tool doesn't process delivery
reports until it has slept -- but the latency is based on the actual time of running the delivery report callback,
not the time the response was accepted by rdkafka.
Fix this problem by replacing the sleep with a busy loop that polls (with a hand-wavy timeout of at most …
> rdkafka_performance: Don't sleep while waiting for delivery reports

- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_broker.c
- src/rdkafka_cgrp.c
- src/rdkafka_int.h
- src/rdkafka_queue.h
- src/rdkafka_timer.c
- src/rdkafka_topic.c
- tests/0084-destroy_flags.c
- tests/CMakeLists.txt
- tests/test.c
- tests/testshared.h
- win32/tests/tests.vcxproj
From Dispose() you would call `rd_kafka_destroy_flags(RD_KAFKA_DESTROY_F_NO_CONSUMER_CLOSE)`.
This should probably be changed in the Python destructor as well.
> Add rd_kafka_destroy_flags()

- src/rdatomic.h
- src/rdkafka.c
- src/rdkafka_queue.c
- src/rdtime.h
- src/tinycthread.c
- src/tinycthread.h
The timeout_ms parameter was reused as-is in certain loops, causing the timeout to never actually decrease.
This PR fixes this, and optimizes a few other places, to use an absolute end time instead.
Also chucked in an unrelated atomic fix for good measures.
Testing revealed that rd_kafka_flush() was unnecessarily slow, so fixed that as well.
> Fix timeout reuse in queue calls (#1863)

- examples/rdkafka_performance.c
I wanted to use the performance tool to stress our application, which requires messages with specific content (JSON, authorization parts, types, ...). Using `-m` to specify the JSON was easy, but I found it very counter-intuitive that it would repeat the pattern/cut it off unless I explicitly also specified the length.
This PR changes this behavior so that the length gets adjusted by default when `-m` is used. A user that wants cut-off/repeat can specify the length as before by setting it _after_ the `-m` switch.
For my purposes this is enough, but it would break uses where the caller runs `rdkafka_performance -s SIZE -m PATTERN`. One approach for avoiding this breakage would be track whether the user set the size explicitly, and only update in `-m` when that is not the case. Thoughts?
> Update the message size when a pattern is provided via -m

- src/rdkafka_conf.c
- src/rdkafka_conf.h
- src/rdkafka_transport.c
The commit adding support for the ssl.sigalgs.list config option (3cc0ab6) checks the version of openssl (`#if OPENSSL_VERSION_NUMBER >= 0x1000200fL`) to determine if the `SSL_CTX_set1_sigalgs_list()` function is available.
Libressl (for some reason) defines the `OPENSSL_VERSION_NUMBER` as `0x20000000L`, but it doesn't (yet) support these newer APIs.
Augment version checks with `&& !defined(LIBRESSL_VERSION_NUMBER)` to compile with LibreSSL.
Closes #1896
> Use `configure` to test for SSL capabilities to support LibreSSL

- CONFIGURATION.md
- src/rdkafka_broker.c
- src/rdkafka_conf.c
We can't restore the connection to a clean state when a partial
request times out, instead fail the connection and reconnect,
regardless of the socket.max.fails setting.
> Disconnect regardless of socket.max.fails when partial request times out (#1955)

- INTRODUCTION.md
Makes the `batch.num.messages` description under the Performance header of INTRODUCTION.md agree with the description in CONFIGURATION.md
> Update batch.num.messages description

- examples/rdkafka_consumer_example.cpp
remove the callback from the high level consumer example since it is not implemented
The callback is not implemented. Yet, it is featured in the example. This is highly confusing as can be shown by these tickets: [HERE](https://github.com/edenhill/librdkafka/issues/1905), [HERE ](https://github.com/edenhill/librdkafka/issues/1137) and [HERE](https://github.com/edenhill/librdkafka/issues/1620).
> Remove callback in KafkaConsumer's example since it is actually not implemeted

- .travis.yml
- configure.librdkafka
- packaging/alpine/test-build-alpine.sh
- packaging/alpine/test-build.sh
- src/CMakeLists.txt
- src/Makefile
- src/tinycthread.c
- src/tinycthread.h
- src/tinycthread_extra.c
- src/tinycthread_extra.h
- tests/0033-regex_subscribe.c
- tests/CMakeLists.txt
- tests/Makefile
- win32/librdkafka.sln
- win32/librdkafka.vcxproj
- win32/tests/tests.vcxproj
When libc provides C11 threads, which is the case with musl on alpine, the internal librdkafka c11 thread implementation (tinycthread), interferes with the musl symbols, leading to weird errors and crashes.
There are no code changes, only refactoring.
This PR makes librdkafka use the system C11 threads if available.
Reported in #1998
> Use C11 threads when available

- src/rdkafka_transport.c
Should fix https://github.com/edenhill/librdkafka/issues/1937
> Fix high cpu sasl loop after disconnect

- src/rdaddr.c
Hi,
We are having some compilation warnings (error in our case since we use -Werror) when linking a program against librdkafka built using LTO and enabling LTO.
We have:
```
In function ‘rd_addrinfo_prepare’,
inlined from ‘rd_getaddrinfo.constprop’ at rdaddr.c:160:17,
inlined from ‘rd_kafka_broker_resolve’ at rdkafka_broker.c:634:19,
inlined from ‘rd_kafka_broker_connect’ at rdkafka_broker.c:1287:6,
inlined from ‘rd_kafka_broker_thread_main’ at rdkafka_broker.c:3328:8:
rdaddr.c:134:3: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
rdkafka_broker.c: In function ‘rd_kafka_broker_thread_main’:
rdaddr.c:129:13: note: length computed here
lto1: all warnings being treated as errors
```
While here gcc is clearly being over-strict (gcc …
> Fix LTO warning with gcc 8.

- examples/rdkafka_performance.c
Removing the deduction of outq len from the total message produced count, which creates unnecessary mismatch between delivered and produced counters if in case there is some messages in outq.
Reference: issue#1542
> Fixing Counting error in rdkafka_performance #1542

- src/rdkafka_transport.c
Changes to be able to build librdkafka with OpenSSL 1.1.0
> OpenSSL 1.1.0 compatibility

- CMakeLists.txt
- packaging/cmake/parseversion.cmake
- packaging/cmake/rdkafka.pc.in
- src-cpp/CMakeLists.txt
- src/CMakeLists.txt
Generate the pkg-config files with CMake.
It uses the configure_file function from CMake to generate the pkg-config files for the C and C++ libraries (shared and optionally static variant) from the same template file.
Since the pkg-config files contain the version, the CMake project version is set.
> CMake: Generate pk-gconfig files

- src/rd.h
- src/snappy_compat.h
Hello Magnus, this addresses an issue on hurd-i386 build failure we had
in Debian.
See https://bugs.debian.org/900716
Build logs https://buildd.debian.org/status/fetch.php?pkg=librdkafka&arch=hurd-i386&ver=0.11.6-1&stamp=1540378777&raw=0
Patch by Samuel Thibault <sthibault@debian.org>
> Fix build failure on hurd-i386

- src/rdkafka_transport.c
OpenSSL v1.1.0 made all of the init stuff optional and deprecated the old functions in favor of `OPENSSL_init_ssl` and `OPENSSL_init_crypto`. There are compatibility macros in place, but only if you compile with openssl's api compatibility switch set.
This change lets librdkafka compile against OpenSSL with the API compatibility level set as late as 1.1.0.
I've only done moderate testing ("it works for me").
> OpenSSL initialization compatibility for v1.1.0 and later

- examples/rdkafka_example.c
- examples/rdkafka_performance.c
This is modelled to match the code in rdkafka_example.c: `-X dump` will dump
the configuration, and then exit the program successfully.
Fixes #1900
> Add an option to dump the configuration

- src/rdkafka_cgrp.c
@mhowlett Please verify this fix with the .NET client
> Consumer: don't send Leave when terminating with NO_CONSUMER_CLOSE (#2138)

- src/rdkafka_lz4.c
I believe 4x is a good constant here. Based on measurements included in the cited reference, it will cover the majority of cases. On the flip side of this, any adjustment up results in meaningfully more memory usage in the scenario i've been testing.
including contentSize in the lz4 frame is marked as a TODO in the java code. we should encourage them to add this, as it would be very beneficial for librdkafka.
> less aggressive lz4 estimated uncompressed size

- packaging/archlinux/PKGBUILD
* Build based on latest tag, as recommended by the packaging guidelines
* pkgver() will automatically override the pkgver value (but a static
value must be defined either way)
* Do a complete build enabling all supported compression algorithms
SSL/TLS for encryption and SASL for authentication. The dependencies
are small enough that there's not much of a point in having them as
optional dependencies, they're likely already installed on the target
system and it avoids a bunch of guessing at runtime to figure out
which capabilities are supported
With the current set of depends we end up with -lsasl2  -lssl  -llz4
-lm -lzstd  -lcrypto  -lz  -ldl -lpthread -lrt as build flags.
> packaging: Fix the Arch Linux PKGBUILD

- src-cpp/rdkafkacpp_int.h
I challenged a small fix. Please confirm it.
Fix issue #1704 (RdKafka::Conf::get(propName, propVal) returns an empty value for topic configuration properties)
> Fix issue #1704

- src/rdkafka_queue.c
Handle additional retvals from cnd_timedwait_abs() to avoid infinite loop.
> Handle additional retvals from cnd_timedwait_abs()

- CMakeLists.txt
- packaging/cmake/config.h.in
- packaging/cmake/try_compile/c11threads_test.c
- packaging/cmake/try_compile/rdkafka_setup.cmake
This PR adds a check in the CMake files to detect C11 thread support on the build host to enable the conditional compilation of tinycthread.
Glibc version 2.28 introduced support for C11 threads, which leads to similar problems as reported in https://github.com/edenhill/librdkafka/issues/1998 on system that already use that Glibc version.
> CMake: Add check for C11 thread support.

- src-cpp/rdkafkacpp.h
Fix for:
In file included from test.cpp:54:0:
/opt/librdkafka/include/librdkafka/rdkafkacpp.h:79:2: warning: extra ‘;’ [-Wpedantic]
};
^
> Update rdkafkacpp.h to fix -Wpedantic warning

- src/rdkafka.c
- tests/0056-balanced_group_mt.c
- tests/0075-retry.c
- tests/sockem.c
- tests/sockem_ctrl.c
With this commit, I can successfully run 'gmake -C tests run_local' on a solaris 11.4 machine; I haven't tested anything further than that.
> Always give a non-NULL result pointer to thrd_join

- CMakeLists.txt
- packaging/cmake/Config.cmake.in
- packaging/cmake/Modules/FindLZ4.cmake
- packaging/cmake/config.h.in
- src/CMakeLists.txt
As mentioned in my last PR (https://github.com/edenhill/librdkafka/pull/2075#discussion_r229286103) this PR adds a CMake option `ENABLE_LZ4_EXT` to enable optional linking with an external LZ4 library.
It uses the CMake find module for LZ4 from https://github.com/Kitware/VTK/blob/master/CMake/FindLZ4.cmake to find the linker options for the LZ4 library.
The librdkafka pkg-config file and CMake package are updated to reflect the option.
Also, a package version file is generated for the librdkafka CMake package (it is optional, but good practice IMO).
> CMake: Enable linking with an external LZ4 library

- src/tinycthread.c
Fixes a pragma leak in tincythread on windows that could poison a dll
> Fix tinycthread const_seg/data_seg pragma mismatch

- src-cpp/rdkafkacpp.h
I clarified the documentation slightly as we had a bug caused by delete being called on a `TopicMetadataVector*`.
> Minor improvements to documentation.

- src-cpp/CMakeLists.txt
Hi! I am creating a portfile for `librdkafka` in `vcpkg` these days. And I encountered several `unresolved external symbol` errors related to those static const data members defined  in `RdKafka::Topic` when I built `librdkafka` as a shared library on Win32: https://github.com/Microsoft/vcpkg/pull/5921#issuecomment-480585430
After some research, I found that this issue seems caused by a redundant `LIBRDKAFKACPP_EXPORTS` definition in this file: https://github.com/edenhill/librdkafka/blob/master/src-cpp/CMakeLists.txt#L37-L39
This redundant definition causes `RD_EXPORT` expanded as `__declspec(dllexport)` in a CMake-based project.
A small CMake project to help reproduce this problem: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/librdkafka_pr_2274
> CMake: Remove redundant LIBRDKAFKACPP_EXPORTS definition

- CMakeLists.txt
- LICENSE.FindZstd
- packaging/cmake/Modules/FindZstd.cmake
- packaging/cmake/Modules/LICENSE.FindZstd
- src/CMakeLists.txt
When built as a static library on Win32, zstd has output names like zstd_static.lib (Release) and zstd_staticd.lib (Debug):
https://github.com/facebook/zstd/blob/69baaee3e42f90dedea2c946bc19bfeac4e782ee/build/cmake/lib/CMakeLists.txt#L141
and `find_library(ZSTD zstd)` will not work in such cases.
> CMake: Take care of zstd static lib on Win32

- src/rdkafka_queue.h
- tests/CMakeLists.txt
- Remove redundant LIBRDKAFKACPP_EXPORTS definition in tests missed in #2274
I want to apologize for it since I should have fixed it in #2274. But I didn't run the tests before: https://github.com/myd7349/vcpkg/blob/8aeafa192dc621f17be56108cabcc556fe6522b9/ports/librdkafka/portfile.cmake#L32, so I just missed it at that time.
We can reproduce the link error caused by this definition on Win32 by:
```
mkdir build
cd build
cmake ..
cmake --build .
```
- Fix C4996 warning related to strdup
When I was trying to build librdkafka on UWP, a C4996 error is reported by VS: 
>e:\vcpkg\buildtrees\librdkafka\src\a34ca9b746-a24f4e04b2\src\rdkafka_queue.h(652): error C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for …
> Minor fixes for Win32

- src/rdkafka_broker.c
- src/rdkafka_idempotence.c
- src/rdkafka_int.h
The logical broker connections (such as to the group coordinator)
are reserved for specific use and shall not be reused for things like
Metadata requests. The code to lookup a usable broker to send
Metadata requests understood this, but the code to select a broker
to create a new connection to if no usable connections are
found (sparse connnections) did not understand this and already
thought there was an active connection (the logical broker connection)
and refused to set up a new one.
This could lead to consumers stalling consumption if it was fetching
from a single broker and that broker went down, no new connection
to the cluster would be made to refresh metadata.
This fixes #2266
> Don't let active logical broker connections hinder new connects (#2266)

- src/snappy_compat.h
https://github.com/google/snappy/blob/1.1.7/snappy-stubs-internal.h#L113-L114
> snappy-c: ARM64 supports direct unaligned loads/stores

- README.md
I've created and released a Common Lisp library on top of librdkafka and would like to list it on the README.
> Add cl-rdkafka to language bindings

- src/rdkafka.c
- src/rdkafka_cgrp.c
- src/rdkafka_int.h
- src/rdkafka_queue.c
Previous to this fix the app_polled time was only updated upon
entry to a (possibly) blocking function, such as consumer_poll().
If the call had a timeout > max.poll.interval.ms and there were no messages
for at least max.poll.interval.ms, the max poll check would kick in and
evict the consumer from the group due to inactivity.
We now signal to app_polled that we're in a blocking call
which prevents the max poll check to fire.
> max.poll.interval.ms: properly handle blocking calls

- src/rdkafka_conf.c
This check was added in the 1.0 release, but it ignores the special value of `message_timeout_ms = 0`, which indicates an infinite timeout. This patch makes the timeout check treat the special value appropriately.
> Fix message timeout check

- src/rdkafka_partition.c
Currently rd_kafka_committed returns list with empty  metadata:
> Fill metadata in rd_kafka_committed & rd_kafka_offsets_for_times.

- src/rdkafka_transport.c
Added socket recv error handling for MSVC build.
There's no returns when recv returns SOCKET_ERROR and error code is not WSAEWOULDBLOCK.
It causes crashes(calls rd_buf_write with size -1).
> Fixed socket recv error handling for MSVC build

- src/rdkafka_partition.c
Fix for #2373.
Call `rd_kafka_handle_Offset` after checking op version and only when err is not `RD_KAFKA_RESP_ERR__OUTDATED`.
> Prevents destroy toppar when retry OffsetRequest

- examples/rdkafka_example.cpp
./rdkafka_example_cpp -L -b 172.17.0.2:9092 -t test_topic
./rdkafka_example_cpp -L -b 172.17.0.2:9092
execute above two commands, the result is the same. The reason is topic!=NULL should be !topic in 661 line
> fix#2425 rdkafka_example_cpp -L to list metadata can't assign topic

- src/rdkafka_ssl.c
ignoring result of SSL_get_verify_result if **enable_verify == false**
lil chore: using SSL_VERIFY_NONE instead of 0 in SSL_CTX_set_verify
if I have a self-signed and expired certificate, then I can’t get the software to work with the option **enable.ssl.certificate.verification = false**, because the **rd_kafka_transport_ssl_verify** function will always return -1 and the process will always try to reconnect
> fix for processing of enable.ssl.certificate.verification

- src/rdkafka_sasl_cyrus.c
When librdkafka is used as a plugin and there is a signal handler that ignores ECHILD for plugins the kinit system call returns a -1 with errno ECHILD.  This can be safely ignored and just means the command finished before the wait for it could be issued.  This fixes an issue with pmacct using librdkafka as a plugin.
> don't fail kinit for ECHILD

- mklove/modules/configure.libzstd
This commit will add an option which will allow you to explicit disable
zstd usage.
> configure: Add option to disable automagic dependency on zstd

- src/rdkafka_broker.c
- src/rdkafka_msg.c
- src/rdkafka_msg.h
- src/rdkafka_topic.c
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1027
This also improves the granularity of message timeout scans to
match the actual message timeout. (#2202)
The minimum effective message timeout will still be 1000ms, but the
granularity after the initial 1000ms is now on millisecond precision.
> Producer: Messages were not timed out for leader-less partitions

- src-cpp/rdkafkacpp.h
- tests/0085-headers.cpp
Change-Id: Ib0aab2e663a6ec63426605f4bfb527a6ee95fd94
https://github.com/edenhill/librdkafka/issues/2431
This proposed fix for the Headers memory leaks in some case.
Have a nice day.
> Fix memory leak in cpp:Headers

- src/rdkafka_buf.h
- src/rdlist.c
rd_tmpabuf_write is sometimes called with a NULL buffer to clone,
leading to UB when calling memcpy.
It doesn't look like the func could just return NULL in this case
either. Almost all the callers ignore the possibility of NULL, or
are interpreting NULL as an allocation failure.
> Fix UBSan errors

- src/rdkafka_cgrp.c
- src/rdkafka_partition.c
- src/rdkafka_partition.h
- src/rdkafka_subscription.c
- src/rdtypes.h
This makes sure that a consumer_poll() call after pause() will not
return any messages.
> Make rd_kafka_pause|resume_partitions() synchronous (#2455)

- src/rdkafka_msgset_reader.c
It is valid for a transaction to both start and end at an abort transaction marker, the check did not previously allow for that case.
> Fixed off-by-one error in aborted txn check

- src/rdkafka_msgset_reader.c
When control messages were skipped the remaining buffer was not consumed
which lead to the messageset parser reading the remaining bytes as
messages, which in best case resulted in parse errors.
There's also some tiny cosmetic changes to keep under 80 cols.
> Fix consumer protocol parse error when using aborted transactions

- src/rdkafka_msg.c
- src/rdkafka_msg.h
- src/rdkafka_partition.c
- src/rdkafka_request.c
- src/rdsysqueue.h
- src/rdunittest.c
The msgq insert code now properly handles interleaved and overlapping
message range inserts, which may occur during Producer retries for
high-throughput applications.
> Fix msgq (re)insertion code to avoid O(N^2) insert sort operations on retry (#2508)

- mklove/modules/configure.builtin
Needed by Debian packaging
Fixes this:
https://www.mail-archive.com/debian-devel-changes@lists.debian.org/msg620872.html
> configure: add --runstatedir for compatibility with autoconf

- src/rdtime.h
`rdtime.h` avoids use of timespec on macos in general, but it was introduced in #7ee0fdcfd . With the latest 10.15 SDK, timespec_get is gone, and the library breaks.
This is a very simple correction, there may be a better way.
```
dyld: lazy symbol binding failed: Symbol not found: _timespec_get
...
Expected in: /usr/lib/libSystem.B.dylib```
> do not call timespec_get on mac

- src/rdkafka_msg.c
- src/rdkafka_partition.c
- src/rdposix.h
- src/rdunittest.c
- src/rdunittest.h
- src/rdwin32.h
- tests/test.c
The common case where the source queue is simply appended
to the destination queue was not optimized, causing O(n) scans
to find the insert position.
Issue introduced in v1.2.1
> Fix producer insert msgq regression in v1.2.1 (#2450)

- src/rdkafka_conf.c
This would've helped here:
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1068
> Add warnings for inconsistent security configuration

- tests/gen-ssl-certs.sh
To reproduce this bug, you should execute in this order:
1) create a new ca-cert
`./gen-ssl-certs.sh ca ca-cert dummy-cn`
2) try to create a client certificate & key without keytool:
`./gen-ssl-certs.sh client ca-cert dummy_client_cert_ dummy_client`
You will get this error message:
fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('ca-cert.srl','r')
After this fix, it should works like expected.
> gen-ssl-certs: fix rdkafka client cert. creation

- src/rdposix.h
This fixes the parse warnings generated by Coverity during a scan.
> Fix Coverity parse warnings

- src-cpp/rdkafkacpp.h
- src/rdkafka.c
- src/rdkafka.h
Along with adding support to the .NET binding for transactions, I'm adding a 'word count' example, which includes significant logic in the rebalance handlers. This has highlighted the need (or more big convenience really) for exceptions to be propagated through to the initiating function call (currently any unhandled exception in a handler will terminate the process). In order to do that, I need an error code to associate with application generated errors.
> Added ERR__APPLICATION

- src/rdkafka_msg.c
For topic configured with message.timestamp.type=LogAppendTime, type should be RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME.
Issue reference: https://github.com/edenhill/librdkafka/issues/2368
> Issue-2368: Correct message timestamp type

- src/rdaddr.h
- src/rdposix.h
Both points that reference FreeBSD should also check for OpenBSD as OS.
I was able to compile the library on OpenBSD with these two minor changes.
> OpenBSD support

- tests/0052-msg_timestamps.c
- tests/CMakeLists.txt
Test 0052 is broken since 01JAN2020 - fix test by generating dynamically expected timestamps
Test executable generated by CMake was rdkafka_test while when generated through configure is test-runner. Rename rdkafka_test to test-runner to be consistent
> Fix test 0052 and rename test executable generated with CMake

- src/lz4frame.c
- src/rdbuf.c
- src/rdkafka_buf.h
- src/rdkafka_lz4.c
- tests/0004-conf.c
- tests/0039-event.c
- tests/0072-headers_ut.c
size_t being an unsigned type, '%zu' is the correct format specifier.
Using '%zd' is technically undefined behaviour (due to sign mismatch).
> Fix format specifier for printing size_t

- examples/consumer.c
- examples/idempotent_producer.c
- examples/kafkatest_verifiable_client.cpp
- examples/producer.c
- examples/producer.cpp
- examples/rdkafka_complex_consumer_example.c
- examples/rdkafka_complex_consumer_example.cpp
- examples/rdkafka_consume_batch.cpp
- examples/rdkafka_example.c
- examples/rdkafka_example.cpp
- examples/rdkafka_performance.c
- tests/test.c
Another minor tweak to a type:
For proper atomicity (with respect to signal handler), the type of variables modified in signal handlers should be 'sig_atomic_t' with 'volatile' qualifier (modifying other types such as a plain 'int' is undefined behaviour even if it works as expected on most platforms). This is atomicity between main code & signal handler i.e. required even in single-threaded program.
In C++ files, used 0 for false and 1 for true respectively just to avoid any confusion and implicit conversions (which is otherwise fine).
sig_atomic_t type is available since C89, so should be reasonably portable.
> Use sig_atomic_t for vars modified in signal handlers

- examples/rdkafka_example.c
- examples/rdkafka_example.cpp
update the usage with the compression codec of lz4 and zstd
> minor fix to rdkafka_example usage: add lz4 and zstd compression codec to usage.

- win32/common.vcxproj
When building without the fix, you get an error:
1>------ Build started: Project: rdkafka_example, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
1>Done building project "rdkafka_example.vcxproj" -- FAILED.
The error is NOT fixed, when re-targeting the solution.
The file common.vcxproj needs to contain the relevant platform toolset definitions, and this is what …
> Fix build of rdkafka_example project for windows, when using Visual Studio 2017/2019

- src-cpp/ConsumerImpl.cpp
- src-cpp/KafkaConsumerImpl.cpp
- src-cpp/ProducerImpl.cpp
I notice there is memory leak in `RdKafka::Producer::create` if `rd_kafka_new` returns `NULL`.
> fix: cleanup conf object if fails creating producer

- src/rdkafka.c
This fix will silence clang warning [-Wstring-plus-int]
```
librdkafka/src/rdkafka.c:369:2: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
_ERR_DESC(RD_KAFKA_RESP_ERR__BEGIN, NULL),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
librdkafka/src/rdkafka.c:366:53: note: expanded from macro '_ERR_DESC'
[ENUM - RD_KAFKA_RESP_ERR__BEGIN] = { ENUM, # ENUM + 18/*pfx*/, DESC }
~~~~~~~^~~~
librdkafka/src/rdkafka.c:369:2: note: use array indexing to silence this warning
```
> Fix clang warning [-Wstring-plus-int]

- src/rdkafka_txnmgr.c
Fixing build errors on `debian:stretch`
```
rdkafka_txnmgr.c: In function 'rd_kafka_txn_set_fatal_error':
rdkafka_txnmgr.c:245:9: warning: implicit declaration of function 'va_start' [-Wimplicit-function-declaration]
va_start(ap, fmt);
^~~~~~~~
rdkafka_txnmgr.c:247:9: warning: implicit declaration of function 'va_end' [-Wimplicit-function-declaration]
va_end(ap);
^~~~~~
```
which breaks the build
```
Creating shared library librdkafka++.so.1
gcc  -shared -Wl,-soname,librdkafka++.so.1 RdKafka.o ConfImpl.o HandleImpl.o ConsumerImpl.o ProducerImpl.o KafkaConsumerImpl.o TopicImpl.o TopicPartitionImpl.o MessageImpl.o HeadersImpl.o QueueImpl.o MetadataImpl.o -o librdkafka++.so.1 -L../src -lrdkafka -lstdc++
Creating static library librdkafka++.a
ar rcs librdkafka++.a RdKafka.o ConfImpl.o …
```
> Fix build break

- .travis.yml
- src/rdkafka_broker.c
- tests/backtrace.gdb
And bump travis integration tests to AK 2.4.0.
And attempt to get a backtrace if tests crash on travis.
> Fix crash on metadata update (regression in txns PR)

- src/rdkafka_cgrp.c
Let the broker enforce it rather than us.
> consumer_group_metadata: allow empty group.ids

- src/rdkafka_buf.h
- src/rdkafka_idempotence.c
Bump the epoch locally, which is okay for the idempotent producer, is not allowed for the transactional producer since the broker needs to track state of each pid+epoch.
However, this is not yet enforced by the broker which leads to inconsistent state and transactional.id states that go into a blocked unusable state.
> Txn producer must bump epoch through broker, not locally.

- STATISTICS.md
This isn't necessarily the correct solution - the current format is inconsistent, using `rxbytes` for brokers and partitions but `rx_bytes` at the top-level. But at the very least this will keep the documentation in line with the behaviour
> Correct statistics names in docs

- src/CMakeLists.txt
CMake may discover libraries, like zlib/openssl/libsasl2 in nonstandard
directories, e.g., if the user has specified the path to a custom build
of one of these libraries via CMAKE_PREFIX_PATH. In these cases, both the
library search paths and the header search paths must be updated, but
the CMake build system was forgetting to update the header search paths
for all libraries besides zstd.
Fix #2451.
Supersedes #2452.
> Support finding headers in nonstandard directories in CMake build

- src/rdkafka_mock.c
- src/rdkafka_sasl_scram.c
Just a minor fixup :) These misspellings generate [warnings](https://lintian.debian.org/tags/spelling-error-in-binary.html) in `lintian` (Debian's package linter).
```
I: librdkafka1: spelling-error-in-binary usr/lib/x86_64-linux-gnu/librdkafka.so.1 offets offsets
I: librdkafka1: spelling-error-in-binary usr/lib/x86_64-linux-gnu/librdkafka.so.1 succesful successful
```
> Fix lintian-detected misspellings

- src/rdkafka.c
- src/rdkafka_cgrp.c
- tests/0091-max_poll_interval_timeout.c
For https://github.com/confluentinc/confluent-kafka-dotnet/issues/1220
This needs to go into v1.4
> max.poll.interval.ms should only be enforced when using subscribe()

- src/rdkafka.c
Fixed the inverted logic testing the return code of rd_kafka_set_fatal_error().   rd_kafka_set_fatal_error() returns 0 on the PREV_IN_PROGRESS error, which is the only error it returns.  
Fixes #2811
> Fix return value of rd_kafka_test_fatal_error()

- src/rdkafka.h
Resolves https://github.com/edenhill/librdkafka/issues/2843
> Clarify reuse restriction on arguments to rd_kafka_produce()

- src/rdkafka_cgrp.c
Querying for the cgrp coordinator does not need to back off when there
are no brokers connected, as no requests were sent. This avoids an
accident of timing that would cause cgrp initialization to wait an extra
turn of the main rdkafka thread loop, which would add an unnecessary
second of latency.
Inspired by c64b652689.
----
Details follow.
The logs that inspired this change are here: https://gist.github.com/benesch/787791fa96cc75660ecb29cd37d49ddc. Warning: there are some additional debugging log lines that I patched in myself.
The relevant lines are these:
```
May 03 00:40:46.553 DEBUG librdkafka: librdkafka: BRKMAIN [thrd:marmoset:9092/0]: marmoset:9092/0: Enter main broker thread
May 03 00:40:47.542 DEBUG librdkafka: librdkafka: CGRPQUERY [thrd:main]: localhost:9092/bootstrap: Group …
```
> Shave another 1s off cgrp initialization

- configure.self
- mklove/modules/configure.base
- mklove/modules/configure.libsasl2
- mklove/modules/configure.libssl
- mklove/modules/configure.libzstd
- mklove/modules/configure.zlib
Two commits in here. Messages reproduced below. The tl;dr is this fixes edenhill/mklove#21 (which was spawned from #556). It seems like the change to configure.base should be incorporated into mklove, but it seems like more mklove development happens in this repository than there?
----
**Fail configuration when requested library isn't present**
If the user specifies --enable-XXX, fail configuration if XXX isn't
present. The prior behavior required the user to manually inspect the
configure output to determine whether the feature was actually enabled.
This was particularly problematic with downstream build systems, like
Cargo with rust-rdkafka, where the configure output is hidden from users
if configuration is successful.
The default behavior remains unchanged; if a user does not …
> Fail configuration when requested library isn't present 

- CHANGELOG.md
- src/rdkafka_assignor.c
- src/rdkafka_roundrobin_assignor.c
- src/rdunittest.c
- src/rdunittest.h
This also adds declarative unit tests of the assignors.
> Fix crash in roundrobin assignor for asymmetrical subscriptions (#2121)

- src/rdkafka_broker.c
> Always log broker errors (unless supressed) regardless of error callback

- src/rdkafka.h
- src/rdkafka_msg.c
This allows non-C languages (like .NET!) to use it without the need of a C compiler.
> Export rd_kafka_message_errstr() as proper symbol, not inline (#2822)

- mklove/Makefile.base
- src-cpp/Makefile
- src/Makefile
This prevents the shared libs to be re-generated on each 'make',
including 'make install', even if there were no changes, which in the case
of 'sudo make install' would create shared libs as the root user messing up the build dir permissions.
> make: don't depend on linker script if not enabled

- src/rdkafka_mock.h
Allow rdkafka_mock.h to be included from c and c++ programs.
> mock: Make rdkafka_mock.h c++ compatible (#2885)

- src/rdkafka_msg.c
Since `RD_KAFKA_MSG_F_FREE_RKM` is not set, the message would not be
freed when `rd_kafka_msg_destroy`.
https://github.com/edenhill/librdkafka/blob/2e53c0f439e7d5ac4ba0b0c772b56308fee8cfa0/src/rdkafka_msg.c#L103-L104
I might very well be missing something about this, but it definitely looks like any messages created with `rd_kafka_message_new` will leak even if `rd_kafka_message_destroy` is called.
> fix: Don't leak messages created by rd_kafka_message_new

- configure
`./configure --LDFLAGS='-Wl,--build-id=none'`
there are two '=' in a configration, then ` name="${opt%=*}"` will Intercept `LDFLAGS=-Wl,--build-id` as `name`. 
so ` name="${opt%%=*}"`may be a good choice to Intercept LDFLAGS out.
> the configure script does not work correctly when configuration is  like "--LDFLAGS='-Wl,--build-id=none'"

- CHANGELOG.md
- src/rd.h
- src/rdkafka.h
- src/rdkafka_msg.c
- tests/0074-producev.c
It is problematic to construct va-arg lists for calling C in some high-level languages that wrap librdkafka, erlang in the case of #2895. 
This new method allows constructing an array of structs instead.
> Add rd_kafka_produceva() using a vtype array as an alternative to va-args

- CMakeLists.txt
When librdkafka is added to a project using `add_subdirectory`, the
include path for CMake modules that is added is incorrect, since it uses
`CMAKE_SOURCE_DIR` - which is the source directory of the root of the
project instead of `CMAKE_CURRENT_SOURCE_DIR`.
This matters not when librdkafka is built standalone (since the two
directories are the same), but when built as a submodule, it prevents
CMake from finding the bundled modules, like FindLibLZ4.cmake.
> Fix incorrect cmake Module path for submodule use

- src-cpp/rdkafkacpp.h
- src/rdkafka.h
- src/rdwin32.h
Building librdkafka with msys2 for win32 (i686) target failed with:
```
librdkafka\src\rdwin32.h:50:17: error: conflicting types for 'ssize_t'
50 | typedef SSIZE_T ssize_t;
|                 ^~~~~~~
In file included from C:/msys64/mingw32/i686-w64-mingw32/include/corecrt_stdio_config.h:10,
from C:/msys64/mingw32/i686-w64-mingw32/include/stdio.h:9,
from C:\workspace\librdkafka\src\rd.h:48,
from C:\workspace\librdkafka\src\crc32c.c:48:
C:/msys64/mingw32/i686-w64-mingw32/include/corecrt.h:52:13: note: previous declaration of 'ssize_t' was here
52 | typedef int ssize_t;
|             ^~~~~~~
```
this patch will fix this issue.
> fix ssize_t definition in mingw32

- configure
- mklove/modules/configure.base
- mklove/modules/configure.builtin
This is for compatibility with autoconf and is required to not break debian packaging builds.
Reported by @vincentbernat
> Added --disable-option-checking (autoconf compat no-op)

- CHANGELOG.md
- src/rdkafka_assignor.c
This is a backport from the kip-54 PR which I believe you've already reviewed.
> Consumer assignors could ignore topics if topic_cnt > member_cnt

- .travis.yml
- CHANGELOG.md
- configure.self
- src/Makefile
- src/regexp.c
The regex code we use on Windows was using global variables and thus either bugged out or was crashed when multiple consumers with wildcard subscriptions were running in the same instance, as reported in numerous .NET issues.
This fix moves the global `g` variable (g for global!) to the `Reprog` object.
> Fix regex crash on Windows

- CHANGELOG.md
- examples/rdkafka_example.c
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_cgrp.c
- src/rdkafka_mock.c
- src/rdkafka_msg.c
- src/rdkafka_msg.h
- src/rdkafka_msgset_reader.c
- src/rdkafka_offset.c
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_partition.c
- src/rdkafka_request.c
- tests/0039-event.c
- tests/0077-compaction.c
- tests/0104-fetch_from_follower_mock.c
- tests/test.c
- tests/test.h
This also refactors and cleans up OP_ERR and OP_CONSUMER_ERR calls.
The broker_id is also useful in our tests.
> Added rd_kafka_message_broker_id() (#2952)

- CHANGELOG.md
- src/rdkafka_broker.c
- src/rdkafka_mock.c
- src/rdkafka_mock.h
- src/rdkafka_mock_handlers.c
- src/rdkafka_mock_int.h
- src/rdkafka_partition.c
- src/rdkafka_request.c
- src/rdkafka_txnmgr.c
- src/rdkafka_txnmgr.h
- tests/0104-fetch_from_follower_mock.c
- tests/test.c
- tests/test.h
.. and a locking fix for transactions.
> Fix consumer stall when partitions are reassigned (#2955)

- src/rdkafka_partition.c
- tests/0112-assign_unknown_part.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
rd_kafka_cgrp_assign calls rd_kafka_toppar_desired_add0 rather than its
wrapper rd_kafka_toppar_desired_add. The "add" wrapper preserves the
invariant that a known topic should never get added to the desired
partitions queue, while the "add0" function does not.
Maintaining this invariant is important for
rd_kafka_topic_partition_cnt_update, which assumes that a toppar is in
either the list of known partitions or the list of desired partitions,
but not both. Violating this invariant results in the situation
described in #2915, where updating assignments can trigger incorrect
"unknown partition" errors.
This patch rearranges rd_kafka_toppar_desired_add/add0 so that add0, in
addition to add, will avoid adding known partitions to the desired
partition list. The enclosed test correctly fails …
> Ensure known toppars do not wind up in desired partitions list

- CMakeLists.txt
- src-cpp/ConsumerImpl.cpp
- src-cpp/HandleImpl.cpp
- src-cpp/KafkaConsumerImpl.cpp
- src-cpp/ProducerImpl.cpp
- src-cpp/TopicImpl.cpp
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
Improve const correctness by allowing Conf pointers to be const-qualified when constructing Handles. fatal_error member functions are now also const-qualified.
> Const correctness

- src/rdkafka_broker.c
Old kafka brokers(<2.1.0) always reports -1 as LastStableOffset.
This prevents librdkafka from emitting EOF messages. Use
HighwaterMarkOffset instead as before.
> Don't rely on LastStableOffset for old brokers

- src-cpp/KafkaConsumerImpl.cpp
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_cgrp.c
- src/rdkafka_cgrp.h
- src/rdkafka_subscription.c
ok, let's see what you think of this.
many less lines of code and much cleaner than adding `RD_KAFKA_RESP_ERR__LOST_PARTITIONS`, which is a good indicator it's better.
> lost partition notification for EAGER rebalance protocol

- src/rdkafka_queue.c
If there are control messages in the topic, rd_kafka_destroy will
hang if only rd_kafka_consume_batch is used, rd_kafka_consume and
rd_kafka_consume_callback don't have this issue.
Release these messages before returning to the application.
> Destroy control messages in batch mode

- examples/rdkafka_complex_consumer_example.c
This config option is deprecated and should no longer be used in examples.
The non-deprecated behavior is implicitly "offset.store.method=broker".
Trying to set "offset.store.method=broker" explicitly gives a warning, and
trying to set "offset.store.method" to anything else is deprecated AND gives
a warning.
However, "offset.store.method=file" is still supported in src/,
and therefore tested. I didn't touch tests/.
Addresses #3016.
> Remove offset.store.method=broker from the examples/ directory.

- src/rdaddr.c
Fix error reported by Memory sanitizer, see https://github.com/ClickHouse/ClickHouse/issues/12990
Backporting fix by @alexey-milovidov from https://github.com/ClickHouse-Extras/librdkafka/pull/1
> Fix for use-of-uninitialized-value in rdaddr.c

- STATISTICS.md
join_state is the spelling used in the outputted JSON
> Fix misspelled join state field in STATISTICS.md

- src/rdkafka_mock.c
- src/rdkafka_msg.h
- src/rdkafka_msgset_writer.c
- src/rdkafka_proto.h
- src/rdvarint.h
- tests/0009-mock_cluster.c
The Message V2 API uses VARINTs, which means we have to use the
*minimal* overhead to sanity check the size of a ProduceRequest.
> rdkafka_mock: fix message v2 overhead sanity check

- src-cpp/rdkafkacpp.h
- src/rdkafka.c
- src/rdkafka.h
See https://github.com/apache/kafka/blob/b937ec75677f8af13bf6fda686f07e9c62cdd20f/clients/src/main/java/org/apache/kafka/common/protocol/Errors.java#L317-L328 for the upstream error code names and descriptions. It looks like `THROTTLING_QUOTA_EXCEEDED ` and `PRODUCER_FENCED ` have not made it into a released broker yet, so we may want to hold off on them until they're released. But the others are documented at https://kafka.apache.org/protocol.html#protocol_error_codes already, and `INVALID_RECORD` in particular is being returned for messages with no keys that are produced to compacted topics.
> add recent additions to kafka broker error codes

- mklove/Makefile.base
- mklove/modules/configure.base
- mklove/modules/configure.libsasl2
- src-cpp/Makefile
1. Add required libraries (zlib, lz4, zstd, openssl, sasl2) to the
pkg-config `Requires` field instead of to `Libs` if they were
discovered via pkg-config. This allows pkg-config (and other tools
built on top of the pkg-config metadata) to see librdkafka's full
dependency graph.
2. Prefix full paths to librdkafka.a with the pkg-config variable
${pc_sysrootdir}. pkg-config automatically applies this prefix to
paths passed to -I and -L, but nowhere else. This means that the
previous link line in the -static.pc files is inconsistent, and
would expand to
-L${pc_sysrootdir}${libdir} ${libdir}/librdkafka.a
3. #include <stddef.h> when checking for sasl so that detection via
pkg-config works. This is needed as sasl.h references some types
that are defined in stddef.h.
> Improve pkg-config support

- examples/rdkafka_performance.c
Currently, the ability to test producing messages with a header in `rdkafka_performance` is broken because of a subtle `getopt` error.  Although the intent is to give the option `-H` an optional argument, what is happening is optarg is always discarding an option even if present since the format string looks like `...HH:` - it never parses the latter part.
There are a couple of considerations:
* [GNU optarg supports optional arguments with a double colon in the format string](https://www.gnu.org/software/libc/manual/html_node/Using-Getopt.html) (would use `H::`) but not all platforms use GNU.
* [the POSIX standard actually forbids GNU-style optional arguments](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02).
Thus IMHO the best approach is to just make …
> fix producer header option

- src/rdkafka_cgrp.c
stdarg.h must included explicitly for va_start and va_end use in old compilers.
Resolve issue:
[https://github.com/edenhill/librdkafka/issues/3115](url)
> stdarg.h included for va_start macro use

- README.md
@edenhill Glad the `c++ API` is finally ready. And welcome to review and comment. 😊
https://github.com/Morgan-Stanley/modern-cpp-kafka
> Add a new C++ client in README

- .travis.yml
Travis CI [officially](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) supports s390x builds, adding support for same.
> Travis s390x support

- src/rdkafka.c
- tests/0116-kafkaconsumer_close.cpp
During termination, the main thread's loop continues as long
as there are ops left to poll, but is also responsible for
terminating the cgrp via `rd_kafka_cgrp_serve`. It is possible
for the loop to exit before the cgrp is terminated if you
unsubscribe and then immediately destroy the rdkafka handle,
which leaves some stray refcnts and hangs.
The solution is to keep the polling loop going as long as
there are remaining ops OR until the cgrp is terminated.
I also discovered a data race while investigating this issue.
TSAN should occasionally catch the race while running the
updated test 0116, but unfortunately it's pretty non-deterministic..
fixes #3127
> main thread should keep polling while cgrp is alive (#3127)

- tests/fuzzers/README.md
- tests/fuzzers/fuzz_regex.c
Hi!
I have been doing some work on fuzzing Librdkafka and also integrating it into OSS-Fuzz (https://github.com/google/oss-fuzz). OSS-Fuzz is service from Google that performs continuous fuzzing of important open source projects. It's completely free and I would be happy to supply fuzzers to Librdkafka to help with the security of the project. By integrating into OSS-Fuzz you will receive bug reports, coverage reports and more from OSS-Fuzz, and all I need is an email(s) from you that will receive the reports. 
I started with a simple fuzzer for a portion of the regex code, but would be happy to extend with more fuzzers if you would like to integrate.
> Added a first fuzzer with purpose of integrating to OSS-Fuzz

- src/rdkafka.h
- src/rdkafka_cgrp.c
- tests/0113-cooperative_rebalance.cpp
- partitions revoked events should never be emitted in the incremental rebalancing case when the assignment is empty.
- in the n_wildcard test it is valid for either one rebalance or two rebalances to be required for the consumers subscription to be updated.
> Incremental rebalancing fixes

- src/rdkafka.h
As far as I can tell, there is no broker-side requirement to perform transactional operations after calling `rd_kafka_init_transactions`, and the client in `examples/transactions.c` works just fine if I insert arbitrary delays between `init_transactions` and `begin_transaction`. It would also be strange if this requirement did exist, because `init_transactions` is meant to be called once at startup and we can't necessarily control the rate of outgoing messages.
> move note about transaction.timeout.ms to begin_transaction

- src/rdkafka_broker.c
Based on the doxygen comment, a newly added broker should probably be returned via the `rkbp` parameter.
> Return added broker in rd_kafka_broker_update

- examples/transactions.c
1. Abort transcation if partitions are lost and commit if they are revoked. 
2. Correctly iterate over all the offsets in the list
> transactions example: minor bug fixes (#3257)

- examples/transactions.c
rd_kafka_begin_transaction called with consumer handle, should be producer instead
> tansactions example: do not use consumer handle for txn api (#3257)

- src/rdkafka_error.h
Some embedded toolchains (uClibc MIPS in this case) will not define va_list before the rdkafka_error.h is loaded. A va_list undefined error stops the compile. Mimicking the other functions in the header, using the "..." syntax, resolves the compile issue with these toolchains, while not breaking other platforms.
> Update va_list reference to match the other functions and fix an embedded compile issue.

- src/rdkafka_sasl_cyrus.c
Like FreeBSD, OpenBSD needs to include `sys/wait.h` for macros like `WIFSIGNALED`.
> Include sys/wait.h for OpenBSD

- CHANGELOG.md
- src/rdkafka.c
- src/rdkafka_metadata.h
- src/rdkafka_metadata_cache.c
As ops on broker queues may have references to the metadata cache's mutex
> Don't destroy metadata cache until brokers are destroyed (#3279)

- src-cpp/HandleImpl.cpp
- src-cpp/rdkafkacpp.h
This change provides  `RdKafka::OAuthBearerTokenRefreshCb::oauthbearer_token_refresh_cb()` with an `RdKafka::Handle*`. This gives the callback the proper `RdKafka::Handle` to call `oauthbearer_set_token()`/`oauthbearer_set_token_failure()`.
I've also updated the docs to more explicitly refer to the `RdKafka::Handle` methods.
Addresses issue: #2607
> Provide RdKafka::Handle* to OAuthBearerTokenRefreshCb callback (#2607)

- CHANGELOG.md
- src/rdkafka_broker.c
As reported in https://github.com/confluentinc/confluent-kafka-python/issues/1043
> Make broker_update() blocking to assure state is synchronized

- src/snappy.c
- src/snappy_compat.h
In incremental_copy_fast_path there is undefined behavior (and in some
other places too).
And under this circumstances gcc10 with -O1 -ftree-loop-vectorize (or
simply -O3), due to loop unroll, generates code that do copy by 16 bytes
at a time for the second loop (MOVDQU+MOVUPS), while this is not correct
since the memory may be overlapped and may be changed in the previous
iteration.
Fix this by eliminating those UB, by using memcpy over direct store/load
since these days direct store/loads looks redundant. Even on ARM [1].
[1]: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67366
Upstream patch: https://github.com/andikleen/snappy-c/pull/22
*NOTE: clang is fine, and other older versions of gcc too*
This bug was found by [ClickHouse](https://github.com/ClickHouse/ClickHouse) test suite.
> Fix possible corrupted decompression of snappy format

- src/rdkafka_metadata.c
- src/rdkafka_timer.c
- src/rdkafka_timer.h
> Increment the backoff exponentially

- src-cpp/RdKafka.cpp
- src-cpp/rdkafkacpp.h
- src-cpp/rdkafkacpp_int.h
- src/lz4.c
- src/lz4frame.c
- src/rd.h
- src/rdavl.c
- src/rdgz.c
- src/rdhdrhistogram.c
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_cgrp.c
- src/rdkafka_request.c
- src/rdkafka_sasl_scram.c
- src/rdlist.c
- src/rdstring.c
- src/rdxxhash.c
- src/snappy_compat.h
- src/tinycthread.c
Sometimes rd_free is called on objects allocated with plain malloc. This is not consistent.
> Be consistent with rd_malloc/rd_free combos.

- CHANGELOG.md
- STATISTICS.md
- src/rdkafka.c
- src/statistics_schema.json
- tests/Makefile
This makes consumer_lag show the committed consumer lag, i.e., the same thing as what existing consumer_lag monitoring applications will see (but without querying the coordinator), and adds a consumer_lag_stored which is the consumer lag based on the stored offset (the to-be-committed offset) which is the lag from the application's point of view.
> Stats: Fix consumer_lag 

- CHANGELOG.md
- src/rdkafka_txnmgr.c
- tests/0105-transactions_mock.c
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1568
> commit_transaction() could succeed for timed out messages

- packaging/mingw-w64/configure-build-msys2-mingw-static.sh
Remove CMAKE_FIND_LIBRARY_SUFFIXES from packaging/mingw-w64/configure-build-msys2-mingw-static.sh
It turns out that this will not cause any issues with the static bundle
Thanks to @SpaceIm for initially pointing it out.
> Remove CMAKE_FIND_LIBRARY_SUFFIXES From MinGW Build Script

- src/rdkafka.c
- src/rdkafka_msg.c
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_partition.c
- src/rdkafka_queue.c
- tests/0122-buffer_cleaning_after_rebalance.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
Summary: This is bug fix for https://github.com/confluentinc/confluent-kafka-python/issues/1013
Issue: Buffer is not cleaned after rebalance if messages are polled using the batch queue method, so the consumer will still get old messages.
Solution: when assign happens, a new op event with type RD_KAFKA_OP_BARRIER will be created, a new version is been created at mean time. If the consumer met this event, will clean the buffer by comparing the version of msgs and the new version just created.
Test passed in local test:
Testing:
[0122_buffer_cleaning_after_rebalance/ 62.283s] ================= Test 0122_buffer_cleaning_after_rebalance PASSED =================
[<MAIN>                      / 63.161s] ALL-TESTS: duration 63160.668ms
TEST 20210224223610 (bare, scenario default) SUMMARY …
> Clean buffer after rebalancing for batch queue

- CHANGELOG.md
- src/rdkafka_broker.c
- src/rdkafka_cgrp.c
- src/rdkafka_request.c
- src/rdkafka_sasl_cyrus.c
- src/rdkafka_timer.c
- src/rdkafka_timer.h
- tests/0081-admin.c
- tests/0116-kafkaconsumer_close.cpp
- tests/test.c
I think the broker wakeups might also fix #2912
> Don't call kinit cmd from rd_kafka_new()

- src/rdkafka_msgset_reader.c
Per [gitter convo](https://gitter.im/edenhill/librdkafka?at=6051d19d28e6153d7224c665) this debug statement prints the same value (`rd_kafka_q_len(&msetr->msetr_rkq)`) twice, when it seems one of these values should be the length of the parent queue.
> Fix qlen value in debug statement

- src-cpp/CMakeLists.txt
- src/CMakeLists.txt
Per @edenhill comment [here](https://github.com/confluentinc/confluent-kafka-go/pull/564#discussion_r614670205), when building static pkg-config files, add any additional linker flags for dynamic dependencies, e.g. `-ldl` on *nix, `-lws2_32` on Windows, to `Libs`, not `Libs.private`. As this only affects CMake static builds, the risk is minimal (nothing uses these builds yet, but the hope is that confluent-kafka-go will be able to use static MinGW-built artifacts to provide Windows support)
> CMake: Remove Libs.private entries from rdkafka-static.pc and rdkafka++-static.pc

- CHANGELOG.md
- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_transport.c
.. by adding a new SSL_HANDSHAKE broker state specific to this state of
the connection establishment.
> Fix SSL handshake busy-loop due to POLLOUT being set in CONNECT state

- CHANGELOG.md
- src/rdkafka_msgset_reader.c
Seems like there is a case where aborted transactions will have an
ABORT ctrl message marker, but not be included in the aborted transactions
list.
This would cause the next aborted-transaction-offset to be popped from the
aborted transaction list even though it did not match the aborted transaction
marker. This in turn could lead to aborted messages for subsequent aborted
transactions in the same MessageSet to not be skipped and instead delivered
to the application.
The fix is to silently (unless debug) ignore these unsolicited abort markers
if they're not in the aborted transaction list and not pop off the next
non-matching offset from the aborted transaction list.
> Correctly handle empty aborted transactions

- .travis.yml
- packaging/nuget/packaging.py
- tests/0105-transactions_mock.c
That CI test failure has been bugging me for ages, but not being able to reproduce locally until today with a hefty dose of valgrind and cpulimit. Time-based tests are crap.
> Fix static windows build artifacts, and a CI test failure

- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0113-cooperative_rebalance.cpp
The increase in session.timeout.ms surfaced the fact that we don't leave the group on unsubscribe in the incremental case.
> cooperative-sticky consumer unsubscribe() now leaves the group

- src/rdkafka_sasl_cyrus.c
It fixes the issue https://github.com/edenhill/librdkafka/issues/3430
Basically if one has a cached kerberos ticket and disables relogin then sasl should be marked as ready and there should be no first attempt to refresh the ticket.
> Mark sasl ready if relogin disabled

- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0030-offset_commit.c
This regression was introduced in v1.7.0
> Timed auto commits did not work when using only assign() and not subscribe()

- .appveyor.yml
- CHANGELOG.md
- packaging/RELEASE.md
- packaging/nuget/packaging.py
- packaging/nuget/templates/librdkafka.redist.targets
- src/rdkafka_ssl.c
- vcpkg.json
- win32/librdkafka.autopkg.template
- win32/librdkafka.sln
- win32/librdkafka.vcxproj
- win32/packages.config
This addresses the zlib upgrade in #2934 and makes sure we'll have up-to-date dependencies going forward.
It also makes adding additional dependencies easier.
> Use vcpkgs for dependencies on Windows

- CHANGELOG.md
- src/rdkafka_cgrp.c
If a consumer group rebalance takes longer than `session.timeout.ms` (for example, one of the consumers is taking a long time to complete a batch of messages), then other consumers will fail their session timeout check after some time. This is because heartbeat responses from the broker with a `REBALANCE_IN_PROGRESS` error do not update the session timeout.
This PR simply updates the timer when `REBALANCE_IN_PROGRESS` is received in a heartbeat response.
There was a similar improvement in the Java client here: https://github.com/apache/kafka/pull/8834
That change modified the broker to send no error in response to heartbeats during a rebalance, but this PR should fix the issue for clients of older brokers.
> Keep session alive during long consumer group rebalances

- CHANGELOG.md
- mklove/modules/configure.zlib
The test program that is used at compile-time to detect whether zlib is available fails to compile due to `NULL` being undefined:
```
_mkltmpyos55w.c:5:20: error: use of undeclared identifier 'NULL'
z_stream *p = NULL;
^
1 error generated.
```
This means that zlib availability is only automatically detected when using pkg-config.
Import `stddef.h` (which defines `NULL`) in the test program, allowing zlib to be automatically detected via a compilation check.
> mklove: make zlib test program compilable

- .gitignore
- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_conf.c
- src/rdkafka_ssl.c
- src/rdkafka_transport.c
- src/rdkafka_transport.h
- src/rdkafka_transport_int.h
- src/tinycthread_extra.c
- src/tinycthread_extra.h
We've seen an increase in concerns about the internal localhost TCP connections that we use to wake up internal queue listeners.
This here PR changes the IO/queue scheduler to use WSAWaitForMultiplEvents() on Windows, allowing a single call
to wait for both socket IO and queue cond-var signals. Thanks to this the localhost TCP connections are no more.
Manual testing showed a 5-10% throughput increase for the producer.
> Use native scheduler on Windows

- CHANGELOG.md
- packaging/nuget/packaging.py
- packaging/nuget/requirements.txt
- src-cpp/rdkafkacpp.h
- src/rdkafka.h
- Verify artifact file contents and architectures.
- Verify that artifact attributes match.
- Get README, CONFIG,.. etc, from artifacts instead of local source tree
(which may not match the released version).
> Improve nuget release script

- .travis.yml
- CHANGELOG.md
.. which causes older versions of OpenSSL+curl to fail to download OpenSSL..
> Travis: bump Linux base builder from trusty to xenial to circumvent ISRG cert expiry

- src/rdkafka_op.c
Fix a memory leak introduces in ca1b30e0 in which the arguments to an
admin request were not being freed. Discovered by the test suite for
rust-rdkafka [0].
[0]: https://github.com/fede1024/rust-rdkafka/pull/397/checks?check_run_id=3914902373
> Fix memory leak in admin requests

- .travis.yml
- packaging/mingw-w64/configure-build-msys2-mingw-static.sh
- packaging/mingw-w64/run-tests.sh
> Fix MinGW Travis build issues

- INTRODUCTION.md
- src/CMakeLists.txt
- src/Makefile
- src/rdhttp.c
- src/rdhttp.h
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_conf.c
- src/rdkafka_conf.h
- src/rdkafka_sasl_oauthbearer.c
- src/rdkafka_sasl_oauthbearer_oidc.c
- src/rdkafka_sasl_oauthbearer_oidc.h
- src/rdunittest.c
- tests/0126-oauthbearer_oidc.c
- tests/interactive_broker_version.py
- tests/librdkafka.suppressions
- win32/librdkafka.vcxproj
Retrieve jwt from token provider and forward it to the broker:  the example received from provider is listed as the json below, extract the token key with key work "access_token".
```
{
“access_token”: “eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6ImFiY2VkZmcifQ.eyJleHAiOjE2MzI2ODYwNjAsImlhdCI6MTYzMjY4NTc2MCwic3ViIjoic3ViIn0.yY0F9NUD-MJydlF0NzfNXQtl7gYKO6A-yKM-6_6RTcg”
}
```
Test:
1. The extract jwt from json is tested with unit test.
2. The HTTP(S) request to http server part is tested with the following function which is not added to the unit test part:
```
int unittest_sasl_oauthbearer_oidc (void) {
rd_kafka_conf_res_t res;
rd_kafka_conf_t *conf = NULL;
rd_kafka_t *rk;
char errstr[512];
RD_UT_BEGIN();
conf = rd_kafka_conf_new();
res = rd_kafka_conf_set(conf, …
```
> Retrieve jwt token from token provider

- src-cpp/rdkafkacpp.h
Missing letter in Comsum(p)tion in rdkafkacpp.h docs
> rdkafkacpp.h: fixed typo in docs

- CHANGELOG.md
- src/rdkafka_msgset_reader.c
- tests/0129-fetch_aborted_msgs.c
- tests/CMakeLists.txt
- tests/test.c
- tests/test.h
- win32/tests/tests.vcxproj
Fixes #2993.
This also removes fetch backoffs on underflows (truncated responses).
> MsgSets with just aborted msgs raised a MSG_SIZE error, and fix backoffs

- CHANGELOG.md
- src/rdkafka_buf.c
- src/rdkafka_buf.h
- src/rdkafka_cgrp.c
- tests/0129-fetch_aborted_msgs.c
https://github.com/confluentinc/confluent-kafka-go/issues/650
> Fix rkbuf_rkb assert on malformed JoinGroupResponse.metadata

- src/rdkafka_sasl_oauthbearer_oidc.c
- tests/LibrdkafkaTestApp.py
- tests/cluster_testing.py
- tests/interactive_broker_version.py
- tests/sasl_test.py
Integration test for OAuth/OIDC with AK 3.1.0.
This one has dependency on https://github.com/edenhill/trivup/pull/13, since the OauthbearerOIDCApp is not merged yet, so the build failure is expected.
Local test:
1) 
```
./sasl_test.py 3.1.0
[2022-02-01 17:31:01.344881] KafkaBrokerApp-3: Failed to set RLIMIT_NOFILE(9223372036854775807,9223372036854775807): current limit exceeds maximum limit
[2022-02-01 17:31:01.351036] KafkaBrokerApp-4: Failed to set RLIMIT_NOFILE(9223372036854775807,9223372036854775807): current limit exceeds maximum limit
[2022-02-01 17:31:01.358083] KafkaBrokerApp-5: Failed to set RLIMIT_NOFILE(9223372036854775807,9223372036854775807): current limit exceeds maximum limit
PASSED  OAuth/OIDC @ 3.1.0                                : All 1/1 tests passed as expected
```
2) …
> Integration test for OIDC

- tests/test.c
Fixes: #3699
Signed-off-by: Ladislav Macoun <ladislavmacoun@gmail.com>
> Replace deprecated zookeeper flag with bootstrap

- src/rdkafka_broker.c
C short-circuit evaluation seems to cobble the message timeout scanning condition in rd_kafka_broker_producer_serve such that instead of first iteration only (as intended according to adjacent code comment) you get a timeout in the first and second, so typically two scans instead of one
The side effect appears to have been introduced in https://github.com/edenhill/librdkafka/commit/8af1b39842de8baf61ef9612b9b730f8d455c713 and getting rid of it is a minor optimisation, but consideration worthy for high-partition count topics
> Save one superfluous message timeout toppar scan

- packaging/rpm/mock-on-docker.sh
mock epel-8-x86_64 is now broken in fedora:33:
https://bugzilla.redhat.com/show_bug.cgi?id=2049024
Update to fedora:35 with mock configs:
centos+epel-7-x86_64
centos-stream+epel-8-x86_64
> Update to fedora:35 to fix the CentOS 8 build

- src/rdkafka.h
- src/rdkafka_admin.c
- tests/0080-admin_ut.c
- tests/0081-admin.c
If some kinds of enums like ANY or MATCH are passed when creating an AclBinding, an error should be given before calling the CreateAcls operation on the Kafka broker, in order to return a better explaination, because in these cases it returns an "unknown error". Also when a different value is returned from a future version of Kafka that value is mapped to UNKNOWN.
The ACL binding destroy array function is added too
> fix: acl binding enum checks

- .travis.yml
- packaging/mingw-w64/configure-build-msys2-mingw.sh
My stab at fixing the issues highlighted in the #3607 chat recently. When running locally, the two librdkafka DLLs were the only issue. Copying the DLLs to the same folder as the EXE is a much more common practice on Windows than adding the folder the DLLs live in to PATH, so I'm giving this a shot.
> Make dynamic MinGW build copy DLLs instead of trying to manipulate PATH

- src/rdkafka_broker.c
- src/rdkafka_offset.c
- src/rdkafka_offset.h
- src/rdkafka_op.h
- src/rdkafka_partition.c
> Include broker_id in offset reset logs and corresponding consumer errors

- CHANGELOG.md
- STATISTICS.md
- examples/rdkafka_performance.c
- src/rdkafka.c
- src/rdkafka_broker.c
- src/rdkafka_buf.h
- src/rdkafka_conf.c
- src/rdkafka_conf.h
- src/rdkafka_mock.c
- src/rdkafka_mock.h
- src/rdkafka_mock_handlers.c
- src/rdkafka_msg.c
- src/rdkafka_msg.h
- src/rdkafka_msgset_reader.c
- src/rdkafka_partition.c
- src/rdkafka_partition.h
- src/rdkafka_queue.h
- src/rdkafka_transport.c
- src/rdposix.h
- src/rdwin32.h
- tests/0055-producer_latency.c
- tests/0101-fetch-from-follower.cpp
- tests/test.c
- tests/testshared.h
- vcpkg.json
> Improve (and fix) producer queue wakeups

- src/rdkafka.h
- src/rdkafka_queue.c
- tests/0039-event.c
> Handle absent log.queue gracefully in rd_kafka_set_log_queue

- src/rdkafka_conf.c
Undefined behaviour error:
```
rdkafka_conf.c:2866:21: runtime error: index 20 out of bounds for type 'struct (anonymous struct at rdkafka_conf.c:87:9) const[20]'
```
> fix undefined behaviour in config parsing

- src/rdatomic.h
Using InterlockedCompareExchange64() in rd_atomic64_get() on Windows, because reading 64bit value on 32bit platform is not atomic. This avoids errors when calculating max poll timeout
> Fix MAXPOLL error on Win32 (#3537)

- mklove/modules/configure.base
- mklove/modules/configure.libcurl
Needed for static linking, such as in the Go client.
> Fix libcurl dependencies on OSX

- CHANGELOG.md
- src/rdkafka_assignor.c
- src/rdkafka_assignor.h
- tests/0132-strategy_ordering.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
If multiple strategies are supported, the first strategy would be used. But `range` one is always used at this moment. This PR will fixed this issue.
TESTS: TESTS=0132 ./run-test.sh valgrind
```
[0132_strategy_ordering      / 12.606s] ================= Test 0132_strategy_ordering PASSED =================
[<MAIN>                      / 13.410s] ALL-TESTS: duration 13393.378ms
TEST 20220419071425 (valgrind, scenario default) SUMMARY
#==================================================================#
| <MAIN>                                   |     PASSED |  13.411s |
| 0132_strategy_ordering                   |     PASSED |  12.604s |
#==================================================================#
[<MAIN>                      / 14.009s] 0 thread(s) in use by librdkafka
[<MAIN> …
```
> Strategy ordering bug fix

- src/rdkafka.c
`rdkafka.c:4381:63: error: adding 'int' to a string does not append to`
> fix compilation error (minor)

- CHANGELOG.md
- src/rdkafka_request.c
We experience this issue when main thread cgrp start to do a rebalance
and failed when parsing metadata, the cgrp callback will be lost 
and result in consumer unassigned.
If rd_kafka_handle_Metadata failed and will not retry, need to enque 
the callback with err.
> Fix: fix callback missing when metadata request failed

- .github/workflows/base.yml
- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0113-cooperative_rebalance.cpp
https://github.com/confluentinc/confluent-kafka-go/issues/767#issuecomment-1107465737
> Allow any form of unassign*() during consumer close

- configure.self
- mklove/Makefile.base
- src/CMakeLists.txt
- src/Makefile
- src/rdkafka.c
- src/rdkafka_conf.c
- src/rdkafka_sasl_oauthbearer.c
- src/rdunittest.c
- src/win32_config.h
Building RPM packages on CP centos8 builders caused librdkafka-static.a not to be generated because all dependencies were provided by RPMs. But librdkafka-static.a is included in the librdkafka.spec RPM file, so RPM packaging failed.
This PR makes sure librdkafka-static.a is always generated; if there are no dependencies to link statically it will just be identical to librdkafka.a.
.. and some other minor build fixes.
> Fix librdkafka-static.a generation

- CMakeLists.txt
- packaging/cmake/Config.cmake.in
- packaging/cmake/config.h.in
> Enable OauthBearer support when librdkafka is built with Curl and SSL using CMake

- src/rdkafka_transport.c
Not resetting the signalled event caused the next call(s) to
WSAWaitForMultipleEvents() to wake-up immediately, causing increased CPU usage.
Reported in https://github.com/confluentinc/confluent-kafka-dotnet/issues/1809
This is a v1.9.0 regression, so no changelog entry.
> Must call ResetEvent() for WaitForMultiplEvents()-polled cndvars

- packaging/nuget/templates/librdkafka.redist.targets
This just affects the release.py script.
> NuGet librdkafka.redist.targets bumped to v142 (#3881)

- mklove/modules/configure.libssl
As mentioned in the issue #3867 
On m1 MacOS homebrew is located in a different place, so configure script is not able to locate libssl and libcrypto.
This change makes it possible to use those libraries during build on M1.
> OpenSSL libraries path for M1 MacOS

- .semaphore/semaphore.yml
This updates the Semaphore pipeline to use the `s1-prod-macos-arm64` build agent. This new agent was created in a more scalable and maintainable way than the old one.
> use s1-prod-macos-arm64 semaphore build agent

- CHANGELOG.md
- src/rdkafka_idempotence.c
- src/rdkafka_idempotence.h
- src/rdkafka_int.h
- src/rdkafka_txnmgr.c
- src/rdkafka_txnmgr.h
- tests/0105-transactions_mock.c
This is a collection of fixes developed while running different long running chaos tests with single and multiple brokers and several configurations. 
* When requesting an abort with drain and bump after message timeouts, the bump was executed first, causing a series of retries on InitProducerIdRequest until a transaction timeout happen and the producer was fenced. This commit changes the order of the operations, starting the drain bump after the complete transaction ack.
* While a commit operation was in queue, a timeout happens that can cause an abort. The state changes from COMMITTING_TRANSACTION to ABORTABLE_ERROR to ABORTING_TRANSACTION. When the broker comes up the error is permanent or fatal because the state has changed from the initial one.
* When doing a drain and bump …
> Fix for fenced producer after disconnection

- CHANGELOG.md
- mklove/modules/configure.zlib
Updated zlib download url from https://zlib.net/ to https://zlib.net/fossils/ as the former doesn't work for all the versions anymore
> Updated zlib download url (#4024)

- src/rdkafka.h
This is not remotely the result of an exhaustive proofread; just fixed a couple in `rd_kafka_poll` because I was reading it, and then a few more instances that I saw while reviewing _that_ diff.
> Fix some comment typos. NFC.

- src/CMakeLists.txt
Similar to https://github.com/edenhill/librdkafka/pull/3909, but somewhat more consistent with the surrounding CMake code linking to zlib or zstd.
> Fix cURL linking

- src-cpp/HandleImpl.cpp
- src-cpp/MetadataImpl.cpp
- src-cpp/rdkafkacpp_int.h
No functional change intended; just cleaning up compiler warnings.
> rdkafkacpp: Remove bogus semicolons after function bodies.

- .travis.yml
Since it's not generally available across OSX versions
> Disable syslog for static OSX artifacts

- src/rdkafka_conf.h
- src/rdkafka_ssl.c
Sincle 1.7.0 compilation with boringssl  was not working out of the box (see a93482b7ef36d06e9483770e040ff31dbeb9ff74)   
It seems like after 3709caa91391cb115848ef9946ad228aa56ea476 only some tiny switches are needed to make it work again.
See https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md
> Fix compilation with boringssl

- src/rdkafka_broker.c
When the batch.size is exceeded, we will close and send the current batch. In case compression is enabled, we "inflate" the batch size by 8x for the purposes of this check.
At least, that's the intent. Currently the condition is reversed: the 8x inflation happens if compression is disabled, not the other way around. The effect is that messages linger for longer than expected in the queue, as if the batch size was 8x larger. They are still sent respecting the batch size however, since this occurs at a different location.
This change reverses the sense of the condition so that the 8x multiplier is applied iff compression is enabled.
> Fix the batch.size condition on the produce path

- CHANGELOG.md
- src/rdhttp.c
- src/rdkafka_sasl_oauthbearer_oidc.c
- tests/0004-conf.c
- tests/0026-consume_pause.c
- tests/0101-fetch-from-follower.cpp
- tests/0102-static_group_rebalance.c
- tests/0105-transactions_mock.c
- tests/0110-batch_size.cpp
- tests/0117-mock_errors.c
Seems ASAN stopped reporting leaks properly, these are from valgrind runs.
> Fix memory leaks (mostly in tests)

- Doxyfile
References to some words such as master/slave, blacklist, whitelist, etc. shoud be avoided. 
References to master branch or blacklist in librdkafka also exist, but removing them would imply higher impact, such as backward uncompatibility when changing topic.blacklist, for example
Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>
> Try to avoid master references when possible

- CHANGELOG.md
- mklove/modules/configure.libcurl
- vcpkg.json
Fixes CVE-2022-35252, CVE-2022-42915, CVE-2022-42916
> Update curl to 7.86.0

- CHANGELOG.md
- src/rdkafka_partition.c
- src/rdkafka_queue.c
- tests/0137-barrier_batch_consume.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
* Added partition comparison while purging messages in consume batch API.
* Made sure that Barrier operation is never skipped due to barrier version in batch API.
* Increase priority of Barrier operation so that it is run as soon as possible after a barrier operation in raised.
Continuation of the PR - https://github.com/confluentinc/librdkafka/pull/4077 as the repo is moved.
> Fixed multiple issues with interaction of BARRIER operation with consumer batch API

- CHANGELOG.md
- packaging/nuget/nugetpackage.py
Updated arch to arm64 for Nuget Linux Arm64 mapping.
> Fix arch for nuget Linux Arm64 mapping

- src/rdkafka_request.c
correctly to avoid errors if version 4 will be implemented.
Receiving the list of supported ApiVersionRequest only if broker max version is less than 3.
> Set the max available ApiVersionRequest version

- tests/0105-transactions_mock.c
While using create_txn_producer for any test, we set the socket.connection.setup.timeout.ms to 5s, see https://github.com/confluentinc/librdkafka/pull/4076/commits/a6a5e53c7cfb6430de7dfafb4a49fc1f8d34bc16 . 
However, for this test, we are setting the mock broker's RTT to 5s, and due to the fact that we might make the ApiVersionRequest twice (once with version 3, and then with version 0 when the first one fails)
> Set socket connection setup timeout in 0105:do_test_txn_concurrent_operations

- CHANGELOG.md
- src/rdkafka_cgrp.c
Breaks a circular dependency from
rko to rktp and back that prevents
the toppar being destroyed.
> Fix close blocked by refcnt in test 0113.

- CHANGELOG.md
- src/rdkafka_request.c
Earlier, we were adding extra tagged fields when the version was a flexver. (The tagged fields are added at a common place, so this was extra)
I've run tests 0081 and 0080
> Fix ListGroup protocol message for ApiVersion >= 3

- CHANGELOG.md
- src/rdkafka_offset.c
- src/rdkafka_offset.h
- src/rdkafka_op.c
- src/rdkafka_queue.c
- tests/0080-admin_ut.c
- tests/0122-buffer_cleaning_after_rebalance.c
- tests/0137-barrier_batch_consume.c
1. Fixes app_offset and store_offset getting updated after reading each messages. This would have resulted in incorrect app_offset and store_offset in case of Barrier op purging some messages.
2. Fixes pause and resume skipping some offsets in case of Barrier op due to the above app_offset update.
> Fixed issues related to store_offset and next_offset during Barrier op in consume batch API 

- src/lz4.c
Update lz4.c from upstream
Fix potential memory corruption with negative memmove() size
[CVE-2021-3520](https://github.com/advisories/GHSA-gmc7-pqv9-966m)
Check also https://github.com/lz4/lz4/pull/972 
Backporting https://github.com/ClickHouse/librdkafka/pull/6
P.S. newer lz4 1.9.4 has a lot of other improvements. Maybe worth upgrading?
> Update lz4.c from upstream

- tests/0086-purge.c
increasing linger ms and reducing second batch size to avoid sending a second batch when the first batch is purged in flight
> Fix test 0086 often failing

- src/CMakeLists.txt
Follow-up of https://github.com/confluentinc/librdkafka/pull/4003
I noticed that the other libraries have their include directories set privately and cURL is the only library also setting the interface include directories, so that's an oversight from me back then.
I have checked that no public API header includes any cURL header, so this will probably not break any build.
> Include cURL headers not publicly, they are only used in .c files

- CHANGELOG.md
- src/rdkafka_partition.c
- tests/8001-fetch_from_follower_mock_manual.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
and the partition is waiting for
a list offsets result
closes #4195
> Fix segfault when a fetch from follower lease expires

- CHANGELOG.md
- src/rdkafka_fetcher.c
- tests/0139-offset_validation_mock.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
A duplicate message can be emitted when a fetch response is received
in the middle of an offset validation request. Solved by discarding
the fetched message if the state is not `ACTIVE`.
> Fix duplicate message on validate offset

- CHANGELOG.md
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_cgrp.c
- src/rdkafka_partition.c
- src/rdkafka_queue.c
- src/rdkafka_queue.h
- tests/0089-max_poll_interval.c
An issue in v2.1.0 was fixed in which max.poll.interval.ms was not honored,
because it was reset on any queue poll, not just consumer poll.
It was changed it so that only certain rdkafka.h functions which were polling
would reset the timer.
However, librdkafka exposes a method rd_kafka_queue_get_consumer, which returns
the consumer queue, and the application can poll this queue for events rather
than calling consume poll. There is no way to distinguish polls to this queue
and an arbitrary queue, and it won't reset the timer.
So, a new field is maintained inside the queue denoting if it might
contain fetched messages, or not. It deals with forwarding of queues, so
if a queue which receives fetched messages is forwarded multiple times,
calling poll on the forwardee will also reset the …
> Add field to rd_kafka_queue which denotes if it contains fetched msgs

- src-cpp/rdkafkacpp_int.h
- 'leader_epoch_' variable is assigned to itself.
> [To run CI] Fix set_leader_epoch

- CHANGELOG.md
- src-cpp/rdkafkacpp_int.h
- 'leader_epoch_' variable is assigned to itself.
> Fix set_leader_epoch (#4266)

- src/rdkafka.c
- src/rdkafka_admin.c
- src/rdkafka_assignor.c
- src/rdkafka_assignor.h
- src/rdkafka_aux.c
- src/rdkafka_aux.h
- src/rdkafka_buf.h
- src/rdkafka_cgrp.c
- src/rdkafka_int.h
- src/rdkafka_metadata.c
- src/rdkafka_metadata.h
- src/rdkafka_metadata_cache.c
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_range_assignor.c
- src/rdkafka_request.c
- src/rdkafka_roundrobin_assignor.c
- src/rdkafka_sticky_assignor.c
- src/rdkafka_topic.c
- src/rdkafka_topic.h
The additional memory is allocated after the public struct and freed together with it, along with nested array memory, through the usage of `rd_tmpabuf_t`.
`mdit->brokers` are sorted by `mdit->brokers[i].id`
`mdit->topics[i].partitions` are sorted by `mdit->topics[i].partitions[j].id`.
> Metadata refactor to add internal fields

- CHANGELOG.md
- src/rdkafka_buf.h
Not being for a nullable field those unsigned varints don't start from 1
> Fix number or bytes skipped when receiving tags.

- src/rdkafka_assignor.c
- src/rdkafka_assignor.h
- src/rdkafka_cgrp.c
- src/rdkafka_metadata.c
- src/rdkafka_range_assignor.c
- src/rdkafka_sticky_assignor.c
- src/rdlist.c
- src/rdlist.h
- tests/0106-cgrp_sess_timeout.c
- tests/0140-cooperative_commit_rebalance.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
This builds on the protocol change PR to add rack awareness to the Sticky Assignor.
I understand that this is quite a large PR, here are the main changes:
1. Start with rd_kafka_sticky_assignor_assign_cb. They match, almost completely, with the Java changes to AbstractStickyAssignor.java in [this PR.](https://github.com/apache/kafka/commit/1f0ae71fb328288152a938aa2a259f9646783f60#diff-2814643946ccefef81f480e1280e9b3e3397f4673166ca1ac47db7e3cb6fb760). Additionally, a struct matching RackInfo in the Java implementation, is added.
2. There are, what I think are two pre-existing bugs in the implementation that I found while porting tests. They are marked in the commit itself as a comment (I will remove the comment after first round of reviews).
3. Unit test addition: tests missing or …
> Add rack-awareness (KIP-881) to sticky-assignor

- src/rdkafka_metadata.c
- src/rdkafka_metadata.h
- src/rdkafka_metadata_cache.c
- src/rdkafka_mock.c
- src/rdkafka_topic.c
- src/rdkafka_topic.h
- src/rdlist.c
- src/rdlist.h
- src/rdstring.c
- src/rdstring.h
- tests/0045-subscribe_update.c
- tests/test.c
This change handles the final part of KIP-881: triggering a rejoin, in case we detect that one of the topics we are subscribed to, has a change in the set of racks of one of its partitions. 
More precisely, 
trigger a rejoin, if 
1. client.rack is set for consumer
2. there exists a partition P of a topic T, such that we are subscribed to T and racks_in_cached_metadata(P) != racks_in_fresh_metadata(P).
As for the implementation details:
1. `rd_kafka_metadata_partition_internal_t` now contain an racks and their count.  
2. `rd_kafka_topic_info_t` now contains a list of `rd_kafka_metadata_partition_internal_t*`
3. Constructors for (2) have been modified for the changes.
For non-regex case (where we look up the topic information from the topic metadata cache), the topic metadata cache entry …
> [consumer] Trigger a rejoin on partition racks' change [KIP-881]

- CHANGELOG.md
- src/rdkafka_metadata.c
- tests/0125-immediate_flush.c
- tests/test.c
Fixes https://github.com/confluentinc/confluent-kafka-python/issues/1581
> Fixed a bug where topic leader is not refreshed in the same metadata call even if the broker is present.

- src/rdkafka.h
- src/rdkafka_admin.c
> Generates a random salt only when RAND_priv_bytes is available

- src/CMakeLists.txt
- src/Makefile
- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_int.h
- src/rdkafka_protocol.h
- src/rdkafka_request.c
- src/rdkafka_request.h
- src/rdkafka_telemetry.c
- src/rdkafka_telemetry.h
- win32/librdkafka.vcxproj
Contains some initial boilerplate for the entire codeflow, please feel free to add more push specific items, I've added the bare minimum for both the protocols. 
I created a new file entirely, as I think it's justified, seeing how we have different ones for things like fetcher, cgrp, idempotence, etc.
The code compiles, but with warnings.
> Add boilerplate for the entire flow

- src/rdkafka.c
- src/rdkafka_mock.c
- src/rdkafka_mock_handlers.c
- src/rdkafka_op.c
- src/rdkafka_request.c
- src/rdkafka_telemetry.c
- src/rdkafka_telemetry.h
There were some memory leaks in mock broker and while terminating. 
Fixes those + adds some missing init stuff + some warnings addressed
> Fix memory leaks [KIP-714]

- src/rdkafka.c
- src/rdkafka_broker.c
- src/rdkafka_broker.h
- src/rdkafka_int.h
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_request.c
- src/rdkafka_telemetry.c
- src/rdkafka_telemetry.h
Main changes:
1. rd_kafka_get_preferred_broker now handles the case when the previous broker was lost
2. termination is handled gracefully, both in terms of clearing resources, and in terms of sending a Push request with the last pieces of information.
To accommodate this:
Makes changes so that the entire state machine runs on the main thread.
Communication with the broker thread (when preferred broker has to be set) and with the app thread (during termination) is done via ops or conditional variables.
Also updates some documentation comments.
> Add broker selection and client termination [KIP-714]

- .gitignore
- CHANGELOG.md
- src/rdkafka_request.c
- tests/0081-admin.c
Fixes https://github.com/confluentinc/confluent-kafka-python/issues/1600
> Fixed ListConsumerGroupOffsets not fetching offsets for all the topic s in a group with Apache Kafka version below 2.4.0.

- CHANGELOG.md
- src/rdkafka_topic.c
and partition is in state active.
Fixes #4375.
> Add destroy call when leader epoch is stale

- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0113-cooperative_rebalance.cpp
e.g. a destroy happens before the first assignment. Only affects the cooperative-sticky assignor.
fixes #4312
> Fix segfault if assignor state is NULL,

- CHANGELOG.md
- mklove/modules/configure.libssl
See #4303. Moving to internal branch for CI.
We will stick to 3.0.11 with this PR (LTS version)
vcpkg doesn't yet have anything greater than 3.0.8, so this is only a partial upgrade.
> OpenSSl partial bump to 3.0.11

- src/rdkafka_mock.c
- src/rdkafka_mock.h
We exposed accidentally rd_ts_t in the publicly exposed API for mock broker as a part of the KIP-580 commit.
Fixes that.
We didn't do a release for this, so public API guarantee is not broker. 
Additionally marks some file-local methods static.
> Fix public API for mock requests

- CHANGELOG.md
- src/rdkafka.c
- tests/0031-get_offsets.c
- tests/test.c
`rd_kafka_query_watermark_offsets` hangs forever if say, the broker is down, and exceeds the timeout in case the RTT > timeout, see the linked issue.
This PR adds a failing test, and then fixes the issue.
This also changes the fact the return value of `rd_kafka_q_serve` was being compared to RD_KAFKA_OP_RES_YIELD, which doesn't make sense to me, since it returns the count of served ops, and RD_KAFKA_OP_RES_YIELD is a positive constant.
Fixes #2588.
> Fix timeout for rd_kafka_query_watermark_offsets

- .semaphore/semaphore.yml
This changes the Semaphore pipeline to macOS 13.5 agents instead of 12.4
> Upgrade to macOS 13.5 Semaphore agents

- Makefile
- mklove/modules/configure.base
using parallelism.
Don't use passed libdir for librdkafka static
dependencies built from source
> Make install dependent on libs to avoid errors

- CHANGELOG.md
- mklove/modules/configure.libssl
We will stick to 3.0.x with this PR (LTS version)
vcpkg doesn't yet have anything greater than 3.0.8, so this is only a partial upgrade.
> Bump openssl version partially to 3.0.12

- INTRODUCTION.md
- examples/consumer.c
- src/rdkafka.c
- src/rdkafka.h
- src/rdkafka_cgrp.c
- src/rdkafka_cgrp.h
- src/rdkafka_int.h
- src/rdkafka_metadata.c
- src/rdkafka_mock_handlers.c
- src/rdkafka_partition.c
- src/rdkafka_partition.h
- src/rdkafka_proto.h
- src/rdkafka_request.c
- src/rdkafka_request.h
- src/rdkafka_topic.c
- src/rdkafka_topic.h
Added Heartbeat Errorcodes, OffsetCommit Request, OffsetCommit Response and fixed multiple issues including segfaults
- Added error handling to ConsumerGroupHeartbeat API
- Added type new errors - UNRELEASED_INSTANCE_ID and UNSUPPORTED_ASSIGNOR
- Added partial acknowledgement flow
- Upgraded OffsetCommit Request and response to v9
- Fixed metadata being called with duplicate topic id
- Fixed next_target_assignment not getting reset to NULL
- Fixed member stuck if fenced during rebalancing
- Fixed segfault with current and target assignment while resetting consumer group
- Fixed segfault due to deleted topic in metadata
- Fixed leave not being called if the consumer without any assignment leaves
> [KIP-848] HB Error Code, Partial ack flow, OffsetCommit Request, Response and various fixes 

- CHANGELOG.md
- packaging/nuget/packaging.py
> Fix pipeline: inclusion of static binaries

- CHANGELOG.md
- src/rdkafka.c
When the main thread loop was awakened less than 1 ms before the expiration of a timeout, it was serving with a zero timeout, leading to increased CPU usage until the timeout was reached. Happening since 1.x
> Fix to main loop timeout calculation leading to a tight loop for a max period of 1 ms

- CHANGELOG.md
- src/rdkafka_partition.c
- tests/0050-subscribe_adds.c
- tests/0145-pause_resume_mock.c
- tests/0145-unnecessary_resume_mock.c
- tests/CMakeLists.txt
- tests/test.c
- win32/tests/tests.vcxproj
Fixed a bug causing duplicate message consumption from a stale fetch start offset in some particular cases.
In case of subscription change with a consumer using the cooperative assignor it could resume fetching from a previous position.
That could also happen if resuming a partition that wasn't paused.
Fixed by ensuring that a resume operation is completely a no-op when the partition isn't paused.
Fixes https://github.com/confluentinc/librdkafka/issues/4637
> Fix duplicate messages when resuming partitions not paused

- CHANGELOG.md
- src/rdkafka_admin.c
- src/rdkafka_cgrp.c
- src/rdkafka_metadata.c
- src/rdkafka_metadata.h
- src/rdkafka_metadata_cache.c
- src/rdkafka_proto.h
- src/rdkafka_request.c
- src/rdkafka_request.h
- src/rdkafka_topic.c
and improved documentation of Metadata functions
> Metadata cache by topic id

- CHANGELOG.md
- src/rdkafka_metadata.c
- src/rdkafka_metadata.h
- src/rdkafka_metadata_cache.c
- src/rdkafka_topic.c
- tests/0146-metadata_mock.c
- tests/CMakeLists.txt
- tests/cluster_testing.py
- tests/test.c
- win32/tests/tests.vcxproj
Metadata cache was cleared on full metadata
refresh, leading to unnecessary refreshes and
occasional `UNKNOWN_TOPIC_OR_PART` errors.
Solved by updating cache for existing or
hinted entries instead of clearing them.
Happening since 2.1.0
> Fix to metadata cache expiration on full metadata refresh

- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0146-metadata_mock.c
A metadata call before member joins
consumer group, could lead to
an `UNKNOWN_TOPIC_OR_PART` error.
Solved by updating the consumer group
following a metadata refresh only in safe states.
Happening since 2.1.0
Closes #4589
> Fix for a wrong error returned on full metadata refresh before joining a consumer group

- CHANGELOG.md
- src/rdkafka_mock.c
- src/rdkafka_mock.h
- src/rdkafka_topic.c
- tests/0143-exponential_backoff_mock.c
- tests/0146-metadata_mock.c
- tests/test.c
- tests/test.h
Metadata refreshes without partition
leader change could lead to a loop of
metadata calls at fixed intervals.
Solved by stopping metadata refresh
when all existing metadata is non-stale.
Happening since 2.3.0
Closes #4577
> Fix to metadata refresh interruption

- CHANGELOG.md
- src/rdkafka_mock.c
- src/rdkafka_mock.h
- src/rdkafka_mock_handlers.c
- src/rdkafka_mock_int.h
- src/rdkafka_op.h
- src/rdkafka_topic.c
- tests/0146-metadata_mock.c
A partition migration could happen,
using stale metadata, when the partition
was undergoing a validation and
being retried because of an error.
Solved by doing a partition migration
only with a non-stale leader epoch.
Happening since 2.1.0
> Fix for an undesired partition migration with stale leader epoch

- CHANGELOG.md
- tests/test.c
- tests/test.h
While using the cooperative assignor, given an assignment is received while closing the consumer
it's possible that it gets stuck in state WAIT_ASSIGN_CALL, while the method is converted to
a full unassign. Solved by changing state from WAIT_ASSIGN_CALL to WAIT_UNASSIGN_CALL
while doing this conversion.
Fixes #4527
> Fix hang in incremental assign during close

- src-cpp/rdkafkacpp.h
- src/rdkafka.c
- tests/0127-fetch_queue_backoff.cpp
> Fix flaky test because of consume returning before the timeout

- CHANGELOG.md
- INTRODUCTION.md
- src/rdkafka_cgrp.c
Added changelog entry and a section in `INTRODUCTION.md`
> [KIP-848] User documentation

- .formatignore
- CHANGELOG.md
- LICENSE.lz4
- LICENSES.txt
- configure.self
- src/README.lz4.md
- src/lz4.c
- src/lz4.h
- src/lz4frame.c
- src/lz4frame.h
- src/lz4frame_static.h
- src/lz4hc.c
- src/lz4hc.h
- src/rdxxhash.c
- src/rdxxhash.h
Updates lz4 from 1.9.3 -> 1.9.4
Process: 
* clean copy of all the lz4* files from 1.9.4 checkout of lz4 into the librdkafka src directory
* copy of xxhash files into rdxxhash files in the same way
* change any refs to xxhash within lz4* files into rdxxhash
* Update changelog and licenses, and configure file
* Run 0017 (compression test)
> Add files for lz4 1.9.4

- CHANGELOG.md
- src/rdbuf.c
- src/rdbuf.h
- tests/0011-produce_batch.c
After the implementation of KIP-320, TopicCnt was sent as a varint in the metadata request. This change caused an overflow issue due to the use of `rd_buf_erase` to erase the remaining bytes. The overflow occurred in the calculation `rbuf->rbuf_size - (rbuf->rbuf_len + rbuf->rbuf_erased)` because `rbuf->rbuf_erased` was non-zero when the buffer was almost full, leading to an overflow condition.
As a result, for certain configurations that caused the buffer to be nearly full, the client was unable to send metadata requests, and it also caused crashes in the .NET client.
> Handle overflow in rd_buf_write_remains

- CHANGELOG.md
- src/rdkafka_partition.c
Issues: #4736
Fix for an idempotent producer error, with a message batch not reconstructed identically when retried. Caused the error message "Local: Inconsistent state: Unable to reconstruct MessageSet". Happening on large batches. Solved by using the same backoff baseline for all messages in the batch.
Happens since 2.2.0
> Fix for an idempotent producer error, with a message batch not reconstructed identically when retried

- .semaphore/semaphore.yml
- mklove/modules/configure.libzstd
Later versions of zstd fail without -lrt, see https://github.com/facebook/zstd/issues/3558 .
This is WIP for checking semaphore result
> Add -lrt while building zstd for centos

- src/rdkafka_fetcher.c
If any toppars have a zero topic id
Set inter.broker.protocol.version to 2.4 with 3.7 and fetch would fail always.
> Fallback to fetch v12 (#10)

- CHANGELOG.md
- INTRODUCTION.md
- examples/.gitignore
- examples/CMakeLists.txt
- examples/Makefile
- examples/elect_leaders.c
- src/rdkafka.h
- src/rdkafka_admin.c
- src/rdkafka_admin.h
- src/rdkafka_aux.c
- src/rdkafka_aux.h
- src/rdkafka_event.c
- src/rdkafka_event.h
- src/rdkafka_op.c
- src/rdkafka_op.h
- src/rdkafka_request.c
- src/rdkafka_request.h
- tests/0080-admin_ut.c
This PR introduces the public API rd_kafka_ElectLeaders, enabling the execution of Preferred or Unclean leader election for specific topic partitions. Additionally, unit tests are also included.
> Added Public API for Preferred/Unclean Leader Election on Topic Partitions

- examples/elect_leaders.c
- src/rdkafka.h
- src/rdkafka_admin.c
- src/rdkafka_admin.h
from external API and avoid exposing internal destructor
> [KIP-460] Remove duplicate ElectLeaders result type

- CHANGELOG.md
- src/rdkafka_fetcher.c
AK 2.7 is the first version implementing Fetch 12, before that it shouldn't fallback to v12, neither check if topic IDs are supported.
Closes #4870
> Fix for a Fetch regression when connecting to Apache Kafka < 2.7

- CHANGELOG.md
- src/rdkafka_sticky_assignor.c
when potential topic partitions are less than number of members.
Closes #4783
> Fix for an infinite loop in cooperative sticky assignor

- CHANGELOG.md
- src/rdkafka_request.c
- tests/0099-commit_metadata.c
Closes: https://github.com/confluentinc/librdkafka/issues/4649.
When retrieving offset metadata, if the binary value contained zeros
and librdkafka was configured with strndup, part of
the buffer after first zero contained uninitialized data
instead of rest of metadata. Solved by avoiding to use
strndup for copying metadata.
Happens since: 0.9.0
> Fix reading metadata with zeros

- CHANGELOG.md
- src/rdkafka_partition.c
- tests/0104-fetch_from_follower_mock.c
Continuation of https://github.com/confluentinc/librdkafka/pull/4616 from an internal branch due to CI issues
> ListOffsetsRequest should only be sent to the leader replica (CI)

- CHANGELOG.md
- src/rdkafka_broker.c
- src/rdkafka_cgrp.c
- src/rdkafka_partition.c
- src/rdkafka_partition.h
Circular dependencies from a partition fetch queue message to  the same partition blocked the destroy of an instance, that happened in case the partition was removed from the cluster while it was being consumed. Solved by purging internal partition queue, after being stopped and removed, to allow reference count to reach zero and trigger a destroy
> Fix to remove fetch queue messages that blocked the destroy of rdkafka instances

- CHANGELOG.md
- mklove/modules/configure.libcurl
- mklove/modules/configure.libssl
Security upgrade for OpenSSL and Curl, CVEs fixed:
OpenSSL
- CVE-2024-2511
- CVE-2024-4603
- CVE-2024-4741
- CVE-2024-5535
- CVE-2024-6119
CURL
- CVE-2024-8096
- CVE-2024-7264
- CVE-2024-6874
- CVE-2024-6197
Closes #4853
> Upgrade linux dependencies

- CHANGELOG.md
- src/rdkafka_sasl_scram.c
as it's already prepended in server sent nonce.
librdkafka was incorrectly concatenating the client side nonce again, leading to [this fix](https://github.com/apache/kafka/commit/0a004562b8475d48a9961d6dab3a6aa24021c47f) being made on AK side, released with 3.8.1, with `endsWith` instead of `equals`.
Happening since v0.0.99
Tested with trivup started with `--sasl SCRAM-SHA-512` parameter and test 0135
> SASL/SCRAM authentication fix: avoid concatenating client side nonce once more

- CHANGELOG.md
- src/rdhttp.c
> Count 'Too Many Requests' as a retriable error

- .semaphore/semaphore.yml
except for the Style check job because it needs clang format 10
> Upgrade semaphore agent to Ubuntu 22.04

- CHANGELOG.md
- src/rdkafka_transport.c
[documentation](https://man7.org/linux/man-pages/man7/tcp.7.html)
says it's needed for socket buffers to take effect, even if in some
cases they could have effect even after connection.
Happening since v0.9.0
> Socket options are now all set before connection

- CHANGELOG.md
- src/rdkafka_ssl.c
- tests/0097-ssl_verify.cpp
in Java this selection is happening in [X509KeyManagerImpl.getAliases]( https://github.com/openjdk/jdk/blob/d8430efb5e159b8e08d2cac66b46cb4ff1112927/src/java.base/share/classes/sun/security/ssl/X509KeyManagerImpl.java#L717)
The field that is checked is `certificate_authorities` extension in TLS 1.3, that was present in `CertificateRequest` in previous versions in TLS and SSL.
> Client cert callback to check if trusted certificate authorities match with client certificate chain

- CHANGELOG.md
- src/rdkafka_metadata.c
- src/rdkafka_mock_handlers.c
- src/rdkafka_offset.c
- src/rdkafka_partition.h
- src/rdkafka_topic.c
- tests/0139-offset_validation_mock.c
* Closes: #4796.
Fix to allow to migrate partitions to leaders with NULL leader epoch.
NULL leader epoch can happen during a cluster roll with an upgrade to a
version supporting KIP-320.
Happening since v2.1.0
* Closes: #4804.
Fix to allow to migrate partitions to leaders with same leader epoch.
Same leader epoch can happen when partition is
temporarily migrated to the internal broker (#4804), or if broker implementation
never bumps it, as it's not needed to validate the offsets.
Happening since v2.4.0
> Allow to migrate partitions to leaders with same leader epoch or NULL leader epoch

- src/rdkafka_ssl.c
without any client certificate set.
> Fix to avoid issuing a warning in case server requests a certificate and client is using SASL authentication only

- CHANGELOG.md
- src/rdkafka_cgrp.c
- tests/0113-cooperative_rebalance.cpp
Closes: #4059.
Commits during a rebalance could cause to lose the assignment if the
generation id was bumped by second join group request.
Solved by not rejoining the group in case an illegal generation error happens
during a rebalance.
Happening since v1.6.0.
See this comment for the explanation of the issue:
https://github.com/confluentinc/librdkafka/issues/4059#issuecomment-2488264020
> Fix assignment lost, on illegal generation, during a commit

- src/rdkafka.c
- src/rdkafka_cgrp.c
- src/rdkafka_conf.h
- tests/0018-cgrp_term.c
- tests/0026-consume_pause.c
- tests/0029-assign_offset.c
- tests/0033-regex_subscribe.c
- tests/0040-io_event.c
- tests/0056-balanced_group_mt.c
- tests/0069-consumer_add_parts.c
- tests/0083-cb_event.c
- tests/0084-destroy_flags.c
- tests/0089-max_poll_interval.c
- tests/0091-max_poll_interval_timeout.c
- tests/0093-holb.c
- tests/0106-cgrp_sess_timeout.c
- tests/0113-cooperative_rebalance.cpp
- tests/0117-mock_errors.c
- tests/0118-commit_rebalance.c
- tests/test.c
- tests/test.h
Closing https://github.com/confluentinc/librdkafka/pull/4749 in favour of this PR.
> [KIP-848] Removed partition.assignment.strategy configuration for the new consumer protocol

- src/rdkafka_int.h
- src/rdkafka_metadata.c
- src/rdkafka_topic.c
- src/rdkafka_topic.h
remove topic id check given it's the zero UUID when topic doesn't exist and it invalidates the new check that avoids the transition exists -> not exists before `metadata.propagation.max.ms`.
For `rd_kafka_topic_set_exists` it's fine to keep it as we're comparing the previous UUID with new one to see if it's a deleted topic that is re-appearing or a completely new one.
> fixup: Use same strategy for updating cache partition metadata

- .semaphore/run-all-tests.yml
- .semaphore/semaphore.yml
- packaging/tools/build-configurations-checks.sh
- src/rdkafka_cgrp.c
- src/rdkafka_mock_handlers.c
especially when changing subscription multiple times in a short timeframe, to ensure the coordinator sees all the changes
> [KIP-848] Improved handling of subscribe and unsubscribe cases, 

- src/rdkafka_cgrp.c
- src/rdkafka_cgrp.h
- tests/0109-auto_create_topics.cpp
in this case the heartbeat is retried with given interval or with exponential backoff if it's the first heartbeat. An error is returned
to the user in this case and isn't sent again for the given heartbeat interval or at least 3 seconds.
> [KIP-848] Handle topic authorization failure on consumer group heartbeat

- CHANGELOG.md
- examples/incremental_alter_configs.c
- src/rdkafka.h
- src/rdkafka_admin.c
- src/rdkafka_admin.h
- src/rdkafka_request.c
- tests/0081-admin.c
This PR intends to add support for Group Resource type for IncrementalALterConfigs API as specified in KIP 848 and extended the DescribeConfigs support till API version 3.
Additional changed the integration test to check for Group Resource Type.
> KIP 848:Extend DescribeConfigs and IncrementalAlterConfigs to support GROUP Config

- src/rdkafka_request.c
by not sending an error message to the user as the authentication will be done on the new broker connection.
Similar to what done on SaslHandshake
> Handle the DESTROY_BROKER error on SaslAuthenticate RPC

- src/rdkafka.c
- src/rdkafka_broker.c
- src/rdkafka_int.h
Remove the override to schedule a connection when there's no existing one as it causes too frequent connection retries in case cluster isn't reachable.
Remove scheduled connections count as the `sparse_connect_random` interval is again effective in any case.
> Add an interval to retry connection to any random broker after interval has passed

- packaging/nuget/requirements.txt
this avoids frequent dependency bot commits.
> Compatible versions for nuget dependencies

- CHANGELOG.md
- src/rdkafka_cgrp.c
Re-open #5055 from an internal branch
> [internal] Add missing wrlock around rd_kafka_metadata_cache_hint call

- CHANGELOG.md
- src/rdkafka_telemetry.c
- src/rdunittest.c
Closes #5103
Metrics aren't duplicated when multiple prefixes match them.
Fixed by keeping track of the metrics that already matched.
> [KIP-714] Fix for duplicate metrics when multiple prefixes are matching

- src/rdkafka.h
- tests/0080-admin_ut.c
- tests/0081-admin.c
Co-authored-by: mahajanadhitya <amahajan@confluent.io>
> [KIP-848] Tests for ListGroups filter to list only given group types

- Makefile
> Revert Makefile to use `sh`, removing the single bashism present

- CHANGELOG.md
- src/rdkafka_mock_handlers.c
- src/rdkafka_request.c
Closes #5179.
Fix issue in GetTelemetrySubscriptions with big-endian architectures where wrong values are read as accepted compression types causing the metrics to be sent uncompressed.
Happening since 2.5.0. Since 2.10.1 unit tests are failing when run on big-endian architectures.
> Fix compression types read issue in GetTelemetrySubscriptions response with big-endian architectures

- src/rdkafka_broker.c
In this PR, the cast to int64_t ensures that the left shift operation is performed using 64-bit arithmetic, and the result will not overflow even if rkbuf_retries is equal to INT_MAX. The resulting value of the left shift operation is then multiplied by retry_backoff_ms, which is an int value. The result of the multiplication will be an int64_t value, which can hold the product of the two operands without overflow.
> Handle Integer Overflow

- CHANGELOG.md
- src/rdkafka.c
- src/rdkafka_int.h
- src/rdkafka_metadata.c
- src/rdkafka_request.c
Closes #5178 .
Re-bootstrap is now triggered only after `metadata.recovery.rebootstrap.trigger.ms`
have passed since first metadata refresh request after last successful
metadata response. The calculation was since last successful metadata response
so it's possible it did overlap with the periodic `topic.metadata.refresh.interval.ms`
and cause a re-bootstrap even if not needed.
It's now more similar to the Java implementation here:
https://github.com/apache/kafka/blob/49ee1fb4f9deb326d82b86d3a047182f7d96ddfa/clients/src/main/java/org/apache/kafka/clients/NetworkClient.java#L1222
> Fix for KIP-1102 time based re-bootstrap condition
