confluentinc/librdkafka

src-cpp/ProducerImpl.cpp
src-cpp/TopicImpl.cpp
src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h

Allow key to be used in pointer and length style.

---

Makefile
rpm/get_version.py
rpm/librdkafka.spec

Build rpm with
```
$ make rpm
```
command.
Process looks like:
1. `Makefile` get current `librdkafka` version.
2. Create tar archive from git.
3. Build SRPM with mock.
4. Build RPM with mock from SRPM.

improve build rpm

---

src/rdkafka_broker.c

dont update rktp_fetch_state on consumer lag request fail

---

configure.librdkafka
examples/rdkafka_example.cpp
src-cpp/Makefile
src/rdaddr.h
src/rdendian.h
src/rdkafka_broker.c
src/rdkafka_transport.c
src/rdsysqueue.h

add changes for portability to AIX

---

src/rdkafka.c

On FreeBSD (and perhaps elsewhere) pthread_cond_init / pthread_mutex_init
do heap allocations that are only freed when the corresponding _destroy
functions are called.
rd_kafka_q_init() calls the init functions, so we must make sure that we
call rd_kafka_q_destroy(), even if the underlying queue is stack-allocated.
This is a slow but steady leak - something like 6MB/hour.

rd_kafka_q_serve: ensure rd_kafka_q_destroy() is called.

---

src-cpp/ConsumerImpl.cpp
src-cpp/Makefile
src-cpp/QueueImpl.cpp
src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h
src/rdkafka.h
src/rdkafka_topic.c

I guess a few of us have had the same idea at the same time :)  This is a different take on adding C++ support for queues.

Add consumer queue support for C++.

---

src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h

Updated Topic::name() and Topic::partition_available() to be const methods.  Updated Handle::name() to be const.

Issue #398 Made name() and partition_available const()

---

src-cpp/ConsumerImpl.cpp
src-cpp/rdkafkacpp.h

This can be used to create a negative offset, like the
RD_KAFKA_OFFSET_TAIL() macro in the C binding.

Add Consumer::OffsetTail().

---

examples/rdkafka_example.cpp
src-cpp/HandleImpl.cpp
src-cpp/Makefile
src-cpp/MetadataImpl.cpp
src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h
tests/0013-metadata.cpp

Merged @eugpermar 's work for issue #221 with latest master in response to #433.

Cpp metadata

---

src/rdkafka.c
src/rdkafka_buf.h
src/rdkafka_queue.c

Tell the compiler about a couple of casts to silence warnings.

Explicit casts to make msvc happy

---

debian/control
debian/librdkafka1.symbols

Misc fixes for Debian packaging

---

debian/control
debian/rules

This reverts commit 003ba22419cbc9d28a35b8041caeb2fa32826594.

Revert "Migrate from our own -dbg package to the automatic -dbgsym package."

---

src/rdkafka_conf.c

`make` changed a bunch of stuff in CONFIGURATION.md other than this one thing.  I'll let you commit a new CONFIGURATION.md at your leisure. :)

Correct reference to global enable.auto.commit in rdkafka_conf

---

tests/gen-ssl-certs.sh

add 4 more steps for generating client java key and certificate

---

src/rdkafka_broker.c
src/snappy.c
src/snappy.h

add snappy function header to be compatible with google snappy

add snappy function header to be compatible with google snappy

---

README.md

Add link to Rust bindings

---

src-cpp/HandleImpl.cpp
src-cpp/QueueImpl.cpp
src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h
src/rdkafka.h
src/rdkafka_partition.c
src/rdkafka_queue.c
src/rdkafka_queue.h
tests/0006-symbols.c
tests/0056-balanced_group_mt.c
tests/run-test.sh
tests/test.c
win32/tests/tests.vcxproj

Add some functionality to support for consuming from partitions using multiple threads.

Multithread partition read support

---

README.md

it's AFAIK the most active of the 3 Node.js projects listed

Updated README.md mentioning node-rdkafka

---

src/rdkafka_sasl_win32.c

Additional changes to support Kerberos authentication from Windows
using SSPI.

SASL: Windows SASL implementation via SSPI (#888)

---

README.md

Updated link to rdkafka-dotnet

---

README.md

Perfect is the most popular Server Side Swift API library and HTTP
server framework and librdkafka was successfully imported to Swift on March, 2017.

Adding Swift to Language Bindings

---

src/rdkafka_sasl_win32.c

The protection level and message size was not being sent back to
the server during the authentication handshake.  This was causing
the first characters of the user principal to be misinterpreted
and could cause authentication errors due to an unknown protection
level if the first character of the username did not have bit 1 set

sasl: protection level and message size not sent

---

src/rdkafka_transport.c

Add TLS SNI (serve name) when connecting with SSL. If the broker is
behind a load balancer, the load balancer can use this information to
locate the right server.
I didn't find an easy way to just get the hostname. When I started, I thought I would just have to use `rd_kafka_broker_name()`, so the patch would have been quite minimal. Since some parsing is needed, maybe the patch is not worth it. As I have other non-SNI client (Scala client), I don't really need the patch yet. If you have doubts, feel free to drop it.

Use SNI when connecting through SSL

---

src-cpp/rdkafkacpp.h
src/rdkafka.h
src/rdkafka_offset.c
src/snappy.c

For https://github.com/confluentinc/confluent-kafka-dotnet/pull/339

Offsets store err fix

---

packaging/nuget/packaging.py
packaging/nuget/release.py
packaging/nuget/templates/librdkafka.redist.props

@edenhill - the nuget package generated from this should be fine, but I should finish testing all usage scenarios before merging.

new nuget package layout + debian9 librdkafka build + simplifying

---

src-cpp/rdkafkacpp.h
src/rdkafka.c
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_cgrp.c
src/rdkafka_metadata.c
src/rdkafka_msg.c
src/rdkafka_msgset_reader.c
src/rdkafka_offset.c
src/rdkafka_op.c
src/rdkafka_partition.c
src/rdkafka_queue.c
src/rdkafka_queue.h
src/rdtime.h
tests/0019-list_groups.c
tests/0021-rkt_destroy.c
tests/0050-subscribe_adds.c
tests/0054-offset_time.cpp
tests/delete-test-topics.sh
tests/interactive_broker_version.py
tests/test.c

One thing lead to another... and we now have a bunch of core-infrastructure bugs fixed in librdkafka.

Timeout fixes, and more.

---

packaging/nuget/templates/librdkafka.redist.targets

fixed .lib paths in nuget packaging

---

src/rdkafka_sasl_plain.c
tests/test.c

Allow arbitrary lengthed (>255) SASL PLAIN user/pass (#1691)

---

src/rdtime.h
tests/0011-produce_batch.c
tests/0026-consume_pause.c
tests/0048-partitioner.c
tests/test.c
tests/testshared.h

 Improve latency by using high-precision QPC clock on Windows 

---

CONFIGURATION.md
src/rdkafka_conf.c
src/rdkafka_transport.c

..due to lacking include files.
Both socket.nagle.disable and socket.keepalive.enable are
now properly ifdef-guarded in the config definition.

socket.nagle.disable=true/TCP_NODELAY was never applied

---

src/rdkafka_sasl_scram.c

OpenSSL offers a more direct API for base64 encoding and decoding.
Previously the code created a couple of BIOs and used the streaming
interface, this results in unneccessary allocations.
Also, we've received a request to integrate this library with TensorFlow
and the base64 BIO interface is one of the things we're trying to trim
from our version of OpenSSL.
Note: if there's an easy alternative to using OpenSSL for base64
processing then I would recommand that. OpenSSL has some odd behaviours
around ignoring whitespace etc. While they don't immediately appear to
matter here, something simplier would be preferable.

Avoid allocating BIOs and copying for base64 processing.

---

src/rdkafka.c
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_op.h
tests/0039-event.c
tests/test.c

.. which allows errors to be emitted as events.
Needed by Golang client issue 200.

Add support for set_events(EVENT_ERROR)

---

STATISTICS.md
src/rdkafka.c
src/rdkafka_partition.c
src/rdkafka_partition.h

And reset app_offset to INVALID when the fetcher is stopped.

Calculate consumer_lag using hi_offset=MAX(app_offset,committed_offset #1878

---

STATISTICS.md

Apply the changes from d8b3004eaccc4063dde767b51e2989e749e259c0:
- "histoor" renamed to "outofrange"
- "mean" removed
- reordered

Update STATISTICS.md to match code

---

packaging/nuget/packaging.py
packaging/nuget/templates/librdkafka.redist.props
packaging/nuget/templates/librdkafka.redist.targets
win32/librdkafka.master.testing.targets

https://github.com/confluentinc/confluent-kafka-dotnet/issues/513

NuGet: change runtime from win7-.. to more generic win-.. (CLIENTS-1188)

---

tests/0084-destroy_flags.c

test unsubscribe doesn't cause destroy_flags to hang

---

src/rdkafka_transport.c

Updates global SSL initialization to only configure callbacks if they
have not already been set. This makes the library behave better in
processes where OpenSSL is being used by other shared libraries, and
will not arbitrarily clobber callback functions set by the main
application using rdkafka.
Also remove call to CRYPTO_cleanup_all_ex_data, which makes an
assumption nothing will utilize OpenSSL in the process anymore and can
cause problems in the scenarios described above.

locking callbacks as required, dont call CRYPTO_cleanup_all_ex_data

---

src-cpp/rdkafkacpp.h

Fixed some small typos in the docs

---

src/rdkafka_proto.h

@edenhill Please review 
1. Updated the  NODE Name size to 256

Error: Local: Host resolution failure #2171

---

src/rdkafka_admin.c

fixes #2154
Co-authored-by: Mickael Maison <mickael.maison@gmail.com>
Co-authored-by: Edoardo Comar <ecomar@uk.ibm.com>

Include error message in CreatePartitions result

---

src/rdendian.h
src/rdkafka_transport.c
src/snappy_compat.h

Without this, I need to run ./configure with CPPFLAGS='-Dsun' for compilation to succeed on Solaris.

Use __sun for detecting Solaris

---

examples/.gitignore
examples/Makefile
examples/rdkafka_idempotent_producer.c
packaging/RELEASE.md
packaging/tools/gh-release-checksums.py
src/rdkafka.c
src/rdkafka.h

And sneaked in a release checksum script.

Idempotent producer example 

---

packaging/cmake/config.h.in
src/rdkafka_broker.c
src/rdkafka_int.h
tests/0095-all_brokers_down.cpp
tests/CMakeLists.txt
tests/test.c
win32/tests/tests.vcxproj

..depending on if they have an address set or not.

Selectively include logical brokers in ERR__ALL_BROKERS_DOWN calculation (#2259)

---

src-cpp/rdkafkacpp.h
src/rdkafka.c
src/rdkafka.h

Update to include error codes from v2.2 of Kafka.

Update error response codes

---

src/rdkafka_msgset_reader.c

Currently, the number of messages in a legacy (v0, v1) message set is used to derive the base offset of the messages. Messages in a message set are not guaranteed to have a consecutive relative offset, which leads to message offsets being overridden by librdkafka and eventually lost to the consumer. The PR changes the usage of the number of messages in the message set to the relative offset of the last message in the set for the calculation of the base offset, which removes the possible inconsistency.

Fix wrong legacy batch absolute offset calculation

---

src/rdkafka_ssl.c

See issue https://github.com/edenhill/librdkafka/issues/2419 for more background

use hostname when validating hostname

---

src-cpp/rdkafkacpp.h
src/rdkafka.h

clarify default behavior of ERR__PARTITION_EOF even/error since v1.0.0

Add documentation about ERR__PARTITION_EOF

---

README.md

DEVX-974: Cross link librdkafka binding repos to examples repo for Cloud

---

src/rdkafka.c

This is not a problem in practice, but the code was wrong, so fixed it.

Tidy up rd_kafka_new() conf freeing to make code clearer (#2478)

---

.travis.yml
Doxyfile
INTRODUCTION.md
src-cpp/rdkafkacpp.h
src/rdkafka.h

Required for cp doc warning->error transition

Fix Doxygen warnings

---

src/rdkafka_msgset_reader.c

This replaces a couple c boolean values (true, false) with the built-in rdkafka boolean values (rd_true, rd_false).

Fix VS 2017 build

---

mklove/modules/configure.builtin

for https://github.com/confluentinc/confluent-kafka-go/issues/339

Add more autoconf compatibility options to ignore

---

configure.self

.. since they pose problems with TSAN

configure: added --disable-c11threads to avoid using libc-provided C11 threads

---

INTRODUCTION.md
README.md
dev-conf.sh

...removed some outdated benchmarks and transferred some wiki pages to the manual.

Add supported KIPs and ApiVersions to manual

---

examples/rdkafka_consumer_example.c
src/rdkafka_msgset_writer.c

..and an unrelated example fix.

Fix assert when using LZ4 with pre-ApiVersionRequest brokers

---

.gitignore
Makefile
configure.self
src/rd.h
src/rdbuf.c
src/rdkafka.c
src/rdkafka_admin.c
src/rdkafka_assignor.c
src/rdkafka_broker.c
src/rdkafka_cert.c
src/rdkafka_cgrp.c
src/rdkafka_conf.c
src/rdkafka_idempotence.c
src/rdkafka_int.h
src/rdkafka_lz4.c
src/rdkafka_metadata.c
src/rdkafka_msgset_reader.c
src/rdkafka_partition.c
src/rdkafka_proto.h
src/rdkafka_ssl.c
src/rdkafka_topic.c
src/rdkafka_transport.c
src/rdposix.h
src/rdregex.c
src/rdstring.h
src/tinycthread_extra.c

https://scan.coverity.com/projects/edenhill-librdkafka?tab=overview
Let's get this merged after 1.2.0

Fixes for issues found by Coverity static code analysis

---

configure.self
dev-conf.sh
src/rdhdrhistogram.c
src/rdkafka_msg.c
tests/0030-offset_commit.c
tests/CMakeLists.txt
tests/Makefile
tests/README.md
tests/run-test.sh
tests/rusage.c
tests/test.c
tests/test.h
tests/until-fail.sh
win32/tests/tests.vcxproj

`make rusage` in tests/ will run the test suite with resource usage threshold checks, this surfaced a busy loop in the producer (test 0076)

Monitor resource usage in tests

---

src/rdkafka_broker.c

Don't trigger error when broker hostname changes (#2591)

---

src/rdkafka_conf.h
src/rdkafka_msgset_reader.c
src/rdkafka_msgset_writer.c

Print compression type per message-set when debug=msg

---

tests/0011-produce_batch.c

Fix test rd_snprintf warnings #2584

---

.appveyor.yml
INTRODUCTION.md
src/rdbuf.c
src/rdbuf.h
src/rdkafka_broker.c
src/rdkafka_buf.c
src/rdkafka_buf.h
src/rdkafka_conf.c
src/rdkafka_conf.h
src/rdkafka_feature.c
src/rdkafka_feature.h
src/rdkafka_mock.c
src/rdkafka_mock_handlers.c
src/rdkafka_mock_int.h
src/rdkafka_op.h
src/rdkafka_request.c
src/rdkafka_request.h
tests/0108-client_swname.c
tests/CMakeLists.txt
tests/LibrdkafkaTestApp.py
tests/Makefile
tests/interactive_broker_version.py
tests/test.c
win32/tests/tests.vcxproj

The JMX metrics read-out in test 0108 was verified with AK trunk as of now.

KIP-511: client.software.name and client.software.version

---

src/rdkafka_broker.c

Prior to this fix the next retry buf time was not considered for the
IO wakeup time, thus blocking up to 1s even if a retry was scheduled sooner
than that, such as is the case with the default retry time of 100ms.
Saw this in a transaction loop where the next transaction's AddOFfsetsToTxnRequest would need to be retried because the previous commit wasn't done, and the retry was scheduled for 1s rather than the configured 100ms.
With the fix in the retry of 100ms is honoured.

Wake up broker thread based on next request retry

---

src/rdkafka_partition.c
tests/0054-offset_time.cpp

leaders_get() could add duplicate partitions in some cases which resulted
in broker returning INVALID_REQUEST for the duplicate partitions.

Fix offsets_for_times() returning INVALID_REQUEST (#2176)

---

Doxyfile
src-cpp/rdkafkacpp.h
src/rdkafka.h

sections don't really work across functions as I had hoped.
A bunch of whitespace cleanups.

Doxygen formatting fixes

---

.travis.yml
dev-conf.sh
examples/idempotent_producer.c
src/crc32c.c
src/rdkafka_broker.c
src/rdkafka_cgrp.c
src/rdkafka_offset.c
src/rdkafka_partition.c
src/rdkafka_request.c
src/rdkafka_topic.c
tests/0101-fetch-from-follower.cpp
tests/0107-topic_recreate.c
tests/CMakeLists.txt
tests/LibrdkafkaTestApp.py
tests/Makefile
tests/README.md
tests/broker_version_tests.py
tests/cluster_testing.py
tests/interactive_broker_version.py
tests/requirements.txt
tests/sasl_test.py
tests/scenarios/README.md
tests/scenarios/default.json
tests/scenarios/noautocreate.json
tests/test.c
tests/test.h
tests/testshared.h
win32/tests/tests.vcxproj

This is a regression from fetch-from-follower.
And a bunch of other fixes.

 Fix produce/consume hang after partition goes away and comes back

---

src/rdkafka_broker.c

Fix stack overwrite (of 1 byte) when SaslHandshake MechCnt is zero

---

packaging/alpine/build-alpine.sh
packaging/tools/build-debian.sh
src-cpp/rdkafkacpp.h
src/rdkafka.h
tests/test.c

And bump version define to v1.5.0..

Avoid test timeouts on CI

---

.dir-locals.el
.gitignore
Makefile
src/crc32c.c
src/rdkafka.c
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_cgrp.c
src/rdkafka_metadata.c
src/rdkafka_metadata.h
src/rdkafka_partition.c
src/rdkafka_request.c
src/rdkafka_topic.c
src/rdlist.c
src/rdlist.h
src/rdunittest.c
tests/0064-interceptors.c
tests/0069-consumer_add_parts.c
tests/test.c
tests/testshared.h

Only trigger consumer group rejoin on complete Metadata responses

---

dev-conf.sh
src/CMakeLists.txt
src/Makefile
src/rdmap.c
src/rdmap.h
src/rdstring.c
src/rdstring.h
src/rdunittest.c
win32/librdkafka.vcxproj

This will be used by the sticky assignor, but thought I'd easen up that future PR by filing this one separately.

Add simple generic and strictly typed hash maps

---

src-cpp/KafkaConsumerImpl.cpp
src-cpp/rdkafkacpp.h
src-cpp/rdkafkacpp_int.h
src/rdkafka.h
src/rdkafka_cgrp.c
src/rdkafka_cgrp.h
src/rdkafka_op.c
src/rdkafka_op.h
src/rdkafka_partition.c
src/rdkafka_subscription.c
src/rdkafka_txnmgr.c
tests/0113-cooperative_rebalance.cpp

Ok, let's see what you think of this.
Previously opened and commented on here: https://github.com/mhowlett/librdkafka/pull/1 . Unfortunately, the rebasing is a bit screwed up over there and i didn't bother to fix it properly. The contextual comments may still be useful to refer back to though.

Incremental assign and unassign

---

.travis.yml
CHANGELOG.md
dev-conf.sh
src/rdkafka_roundrobin_assignor.c
tests/run-test.sh
tests/testshared.h

Fix roundrobin crash (v.1.5.0 regression)

---

CHANGELOG.md
src/rdkafka_broker.c
src/rdkafka_msg.c
src/rdkafka_partition.c
src/rdkafka_partition.h
src/rdkafka_request.c
src/rdkafka_topic.c
src/rdkafka_topic.h
src/rdkafka_txnmgr.c
src/rdkafka_txnmgr.h
tests/0105-transactions_mock.c
tests/0115-producer_auth.cpp
tests/CMakeLists.txt
tests/test.c
win32/tests/tests.vcxproj

And fix a TxnMgr bug it surfaced :fire: .

Add proper producer support for topic authorization failures

---

CHANGELOG.md
src/rdgz.c

Reported by Ilja van Sprundel.

Remove incorrect call to zlib's getInflateHeaders

---

CHANGELOG.md
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_error.c
src/rdkafka_int.h
src/rdkafka_mock.c
src/rdkafka_mock.h
src/rdkafka_txnmgr.c
src/rdstring.h
tests/0105-transactions_mock.c

See commit messages for context

Transactional producer fixes

---

CHANGELOG.md
CONFIGURATION.md
src/rdkafka_conf.c
src/rdkafka_conf.h
src/rdkafka_msg.c
src/rdkafka_topic.c
src/rdkafka_topic.h
tests/0048-partitioner.c
tests/0114-sticky_partitioning.cpp
tests/CMakeLists.txt
tests/test.c
win32/tests/tests.vcxproj

Improves batching of null-keyed messages.

msg: sticky partitioning

---

src/rdkafka_msg.c
src/rdkafka_topic.c

Minor style fixes for sticky partitioning

---

INTRODUCTION.md
src/rdkafka.h

Signed-off-by: Joshua Houghton <joshua.houghton@ripjar.com>

Fix docs, change RD_KAFKA_CONF_RES_OK to RD_KAFKA_CONF_OK

---

CHANGELOG.md
src/rdkafka.c
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_buf.c
src/rdkafka_conf.h
src/rdkafka_coord.c
src/rdkafka_coord.h
src/rdkafka_interceptor.c
src/rdkafka_interceptor.h
tests/0105-transactions_mock.c

It was hairy to get the testcase to trigger the chain of events needed to reproduce the issue, so bear with me on the 0105 test additions.

Fix multiple firings of coord_req leading to crash (ESC4444)

---

CHANGELOG.md
src/rdkafka_metadata_cache.c
src/rdkafka_txnmgr.c
src/rdkafka_txnmgr.h
src/rdsysqueue.h
tests/0105-transactions_mock.c

This also fixes an issue with partition list not remaining sorted in these cases, which could affect subsequent AddPartitionsToTxn reqs.

ESC-4410: Partitions stuck in PEND_TXN state if multiple AddPartitionsToTxn reqs are sent

---

src/rdkafka_broker.c

Force address resolution if the broker epoch changes

---

src/rdkafka_ssl.c

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0020	identifier "CERT_STORE_OPEN_EXISTING_FLAG" is undefined
Error (active)	E0020	identifier "CERT_STORE_PROV_SYSTEM" is undefined
Error (active)	E0020	identifier "CERT_STORE_READONLY_FLAG" is undefined
Error (active)	E0020	identifier "CERT_SYSTEM_STORE_CURRENT_USER"
Error (active)	E0020	identifier "HCERTSTORE" is undefined
Error (active)	E0020	identifier "PCCERT_CONTEXT" is undefined

* include wincrypt.h

---

Makefile

Signed-off-by: F. Aragon <paco@voltanet.io>

Build: avoid interactive 'mv' prompt

---

.travis.yml
packaging/mingw-w64/configure-build-msys2-mingw-static.sh
packaging/mingw-w64/configure-build-msys2-mingw.sh

.. to reduce the build minutes since they're now limited.

Decrease the amount of work being done on Travis-CI

---

CONFIGURATION.md
LICENSE.cjson
LICENSES.txt
configure.self
mklove/modules/configure.base
mklove/modules/configure.cc
mklove/modules/configure.libcurl
src/CMakeLists.txt
src/Makefile
src/cJSON.c
src/cJSON.h
src/rdbuf.c
src/rdbuf.h
src/rdhttp.c
src/rdhttp.h
src/rdkafka.c
src/rdkafka_conf.c
src/rdkafka_sasl_scram.c
src/rdmap.h
src/rdunittest.c
src/rdunittest.h
src/win32_config.h
tests/LibrdkafkaTestApp.py
tests/interactive_broker_version.py
vcpkg.json
win32/librdkafka.vcxproj

This provides the required dependencies for the upcoming KIP-768 work.

cURL and cJSON support

---

CHANGELOG.md
src/rdkafka_admin.c
src/rdkafka_op.h
src/rdlist.c
src/rdlist.h
tests/0055-producer_latency.c

Fix crash in DeleteRecords on request error

---

src/rdkafka.c

Pushing the patch sent by @bnaecker in https://github.com/ClickHouse-Extras/librdkafka/pull/4 to the upstream.
> This is part of a larger set of changes for building ClickHouse on [illumos](https://illumos.org).
>
> illumos does not use the `DT_REG` and friends macros for determining the type of a directory entry. An extra `stat(2)` system call is required, followed by a similar query on the `struct stat` returned from that call.
More details: https://github.com/ClickHouse/ClickHouse/pull/23746

Add support for buildling on illumos

---

CHANGELOG.md
src/rdkafka_buf.h
src/rdkafka_mock.c
src/rdkafka_mock.h
src/rdkafka_mock_handlers.c
src/rdkafka_mock_int.h
src/rdkafka_partition.h
src/rdkafka_proto.h
src/rdkafka_topic.c
src/rdkafka_topic.h
tests/0105-transactions_mock.c
tests/0129-fetch_aborted_msgs.c

Save idempotent producer partition state on partition removal

---

README.md

Also fix indenting of bullet list

Add link to tutorial on Confluent Developer

---

src/rdkafka_broker.c
src/rdkafka_idempotence.c
src/rdkafka_mock.c
src/rdunittest.c

Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

Grooming (compilation warning and potential issue)

---

.appveyor.yml
.travis.yml
CHANGELOG.md
mklove/modules/configure.base
mklove/modules/configure.libcurl
mklove/modules/configure.libssl
mklove/modules/configure.zlib
packaging/RELEASE.md
packaging/rpm/tests/test-on-docker.sh
src/rdkafka.c
tests/0077-compaction.c
tests/0128-sasl_callback_queue.cpp
vcpkg.json

Fix all dependency fallouts since the last release. 😨

Release build fixes

---

src/rdkafka.c
src/rdkafka_broker.c
src/rdkafka_broker.h
src/rdkafka_idempotence.c
src/rdkafka_partition.c
src/rdkafka_sasl_cyrus.c
src/rdkafka_sasl_oauthbearer.c
src/rdkafka_txnmgr.c

This will make troubleshooting easier

Provide reason to broker thread wakeups in debug logs

---

packaging/rpm/mock-on-docker.sh

Add git safe.directory to RPM mock builder too

---

src/rdkafka_admin.c

in rd_kafka_CreateAclsResponse_parse rd_list

fix: correct free

---

CHANGELOG.md
mklove/modules/configure.zlib

Upgrading zlib to v1.2.13

---

CHANGELOG.md
src/rdkafka.h
src/rdkafka_broker.c
src/rdkafka_conf.h
src/rdkafka_interceptor.c
src/rdkafka_interceptor.h

Also verified the behavior with PR https://github.com/morganstanley/modern-cpp-kafka/pull/182

Add interceptor for broker state change

---

README.md

Just found link failure after updating with the latest **1.9.2**

Update build requirements for README.md

---

CHANGELOG.md
packaging/tools/style-format.sh
src/rdkafka_idempotence.c
src/rdkafka_idempotence.h
src/rdkafka_int.h
src/rdkafka_mock.c
src/rdkafka_mock.h
src/rdkafka_txnmgr.c
tests/0105-transactions_mock.c

This is a continuation of @emasab 's #4011

Abort transaction before bumping the epoch

---

README.md

https://github.com/icemachined/kafka-kotlin-native

README: add link to Kotlin Native binding

---

packaging/nuget/templates/librdkafka.redist.nuspec

changed copyright years, owner and urls

Update NuGet Template

---

src/rdkafka_admin.c
tests/0080-admin_ut.c
tests/0081-admin.c

also on duplicate match states

Return error on duplicate partitions

---

mklove/modules/configure.libssl

when OS provided OpenSSL is used

OpenSSL API suppress deprecated in mklove

---

INTRODUCTION.md
src/rdkafka_request.c
tests/test.c

Fix for the 0092 mixed msgver test

---

src/rdkafka_msg.c

exclude the case where the topic is Light-weight

Continuation of #4245

---

src-cpp/rdkafkacpp.h
src/rdkafka.h
vcpkg.json

librdkafka v2.1.1

---

.semaphore/semaphore.yml
src/rdkafka_fetcher.c
src/rdkafka_fetcher.h
src/rdkafka_offset.c
src/rdkafka_partition.c
src/rdkafka_partition.h
src/rdkafka_topic.c
tests/0139-offset_validation_mock.c
tests/Makefile

introduced offset validation position to avoid
touching the next fetch pos that has a different
purpose.

Continuation of #4161

---

CHANGELOG.md

Rewrite changelog for #4261

---

src/rdkafka_assignor.c
src/rdkafka_assignor.h
src/rdkafka_metadata.h
src/rdkafka_range_assignor.c
src/rdkafka_sticky_assignor.c

Added the missing test that is present in Java and removed the FIXMEs

#4252 (KIP-881) Verify number of partitions with rack mismatch

---

tests/0045-subscribe_update.c

once `min_events` are processed in the positive case

[consumer] Trigger a rejoin on partition racks' change [KIP-881]  <- reduce test length by breaking earlier 

---

src-cpp/rdkafkacpp.h
src/rdkafka.h
vcpkg.json

librdkafka v2.2.0

---

src/rdkafka_cgrp.c

- Fix reading error code in CGH_leave due to incorrect parsing of the response.

[KIP-848] Feature branch major comment addressal

---

.semaphore/semaphore.yml
CMakeLists.txt
src/CMakeLists.txt
src/rdkafka_mock_handlers.c
win32/setup-msys2.ps1

and offset leader epoch fix in ListOffsets

Mock handlers: Metadata handler upgrade to version 12

---

.github/CODEOWNERS

Remove kafka-eng as it's too wide.

Update CODEOWNERS to be only clients

---

CHANGELOG.md
src/rdkafka_broker.c
src/rdkafka_broker.h
src/rdkafka_telemetry_decode.c
src/rdkafka_telemetry_encode.c
src/rdkafka_telemetry_encode.h
tests/0113-cooperative_rebalance.cpp
tests/0150-telemetry_mock.c

* Produce request latency metrics
* Add more tests

[KIP-74] Avg and max produce latency plus more tests

---

packaging/cp/check_features.c

Style fixed `check_features.c`

fixup: Ubuntu 24.04 and arm64 linux package verification (#4954)

---

service.yml

fixup: [run-all-tests pipeline] Replace descriptions using double quotes (#5006)

---

INTRODUCTION.md

https://github.com/doxygen/doxygen/issues/9412

Add explicit anchors to make doxygen 1.9.4 work
